import type {InvestmentDecision, InvestmentTrade} from '../../types/api/investment';
import {investmentMoney, investmentTime, profitClass} from './presentation';
const labels: Record<string, string> = {running: '研究中', success: '已结束', failed: '失败', interrupted: '已中断'};
const tools: Record<string, string> = {account: '查看账户', positions: '查看持仓', market_news: '市场新闻', find_stocks: '查找股票', find_boards: '查找行业', board_stocks: '行业股票', analyze_stock: '技术分析', buy_stock: '买入', sell_stock: '卖出'};
export function InvestmentTrades({items}: {items: InvestmentTrade[]}) {
    return <div className="space-y-3">{items.map(t => <article key={t.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-2"><h3 className="text-sm font-semibold text-slate-800">{t.operation.side === 'buy' ? '买入' : '卖出'} · {t.operation.name} · {t.operation.quantity} 股</h3><span className="text-xs text-slate-400">{investmentTime(t.createdAt)}</span></div><p className="mt-2 text-xs text-slate-500">成交价 {investmentMoney(t.result.price)} · 参考日 {t.result.priceDate} · 现金变动 {investmentMoney(t.result.cashDelta)}</p>{t.operation.side === 'sell' && <p className={`mt-2 text-xs font-semibold ${profitClass(t.result.realizedProfit)}`}>本次已实现盈亏 {investmentMoney(t.result.realizedProfit)}</p>}<p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-slate-600">{t.operation.reason}</p></article>)}</div>;
}
export function InvestmentDecisions({items}: {items: InvestmentDecision[]}) {
    return <div className="space-y-3">{items.map(d => <article key={d.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between gap-3 text-xs"><span className="rounded-full bg-slate-100 px-3 py-1 font-semibold text-slate-600">{labels[d.status] || d.status}</span><span className="text-slate-400">{investmentTime(d.createdAt)}</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-slate-700">{d.reason || '正在查看市场与账户…'}</p><p className="mt-2 text-xs text-slate-400">参考价日期 {d.referenceDate}</p>{d.calls.length > 0 && <details className="mt-3 text-xs text-slate-500"><summary className="cursor-pointer">查看研究过程 · {d.calls.length} 次工具调用</summary><ol className="mt-2 space-y-2">{d.calls.map((c, i) => <li key={i} className="rounded-lg bg-slate-50 p-2"><span>{i + 1}. {tools[c.tool] || c.tool}</span><pre className="mt-1 max-h-40 overflow-auto whitespace-pre-wrap break-all text-[11px]">{JSON.stringify({arguments: c.arguments, result: c.result}, null, 2)}</pre></li>)}</ol></details>}</article>)}</div>;
}
