# Generated by Django 5.2.9 on 2026-04-23 12:55

import django.db.models.deletion
import utils.id_generator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='notification',
            table_comment='系统通知表',
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(db_comment='内容', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.CharField(db_comment='消息 ID', default=utils.id_generator.generate_msg_id, max_length=40, primary_key=True, serialize=False, verbose_name='消息 ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_comment='是否已读', default=False, verbose_name='已读'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, db_comment='关联链接', max_length=255, null=True, verbose_name='关联链接'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(db_comment='标题', max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', '信息'), ('success', '成功'), ('warning', '警告'), ('error', '错误')], db_comment='通知类型', default='info', max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(db_comment='接收用户ID', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户'),
        ),
    ]
