# Generated by Codex on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_notification_table_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='逻辑删除时间', null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(db_comment='是否已逻辑删除', default=False, verbose_name='已删除'),
        ),
    ]
