# Generated by Django 5.1.1 on 2026-04-26

import django.utils.timezone
import utils.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('memo_id', models.CharField(db_comment='备忘ID', default=utils.id_generator.generate_memo_id, editable=False, max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='备忘ID')),
                ('content', models.TextField(db_comment='闪念内容', verbose_name='内容')),
                ('mood', models.CharField(db_comment='闪念类型', default='idea', max_length=20, verbose_name='类型')),
                ('source', models.CharField(blank=True, db_comment='闪念来源', default='', max_length=120, verbose_name='来源')),
                ('color', models.CharField(db_comment='展示颜色', default='amber', max_length=20, verbose_name='颜色')),
                ('is_pinned', models.BooleanField(db_comment='是否置顶', default=False, verbose_name='是否置顶')),
                ('is_archived', models.BooleanField(db_comment='是否归档', default=False, verbose_name='是否归档')),
                ('user_id', models.CharField(db_comment='创建者ID', default='admin', max_length=50, verbose_name='创建者ID')),
                ('is_valid', models.BooleanField(db_comment='是否有效', default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(db_comment='创建时间', default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '闪念备忘',
                'verbose_name_plural': '闪念备忘',
                'db_table': 'memos',
                'ordering': ['-is_pinned', '-created_at'],
                'db_table_comment': '闪念备忘表',
            },
        ),
    ]
