# Generated by Django 5.1.1 on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='source',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='mood',
        ),
        migrations.AlterField(
            model_name='memo',
            name='tag',
            field=models.CharField(blank=True, db_comment='闪念标签', default='', max_length=120, verbose_name='标签'),
        ),
    ]
