# Generated by Codex on 2026-06-03

from django.db import migrations, models
from django.db.models import F


def backfill_creator_fields(apps, schema_editor):
    Memo = apps.get_model('memos', 'Memo')
    Memo.objects.update(
        creator_type='user',
        creator_id=F('user_id'),
        creator_name='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_simplify_memo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='creator_type',
            field=models.CharField(choices=[('user', '用户'), ('agent', 'Agent')], db_comment='来源类型：user/agent', default='user', max_length=20, verbose_name='来源类型'),
        ),
        migrations.AddField(
            model_name='memo',
            name='creator_id',
            field=models.CharField(blank=True, db_comment='用户ID或Agent ID', default='', max_length=80, verbose_name='来源ID'),
        ),
        migrations.AddField(
            model_name='memo',
            name='creator_name',
            field=models.CharField(blank=True, db_comment='Agent名称快照；用户来源可为空', default='', max_length=150, verbose_name='来源名称'),
        ),
        migrations.RunPython(backfill_creator_fields, migrations.RunPython.noop),
    ]
