# Generated by Django 5.2.17 on 2026-10-10 22:26

import django.db.models.deletion
import memos.sprout_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0003_add_memo_creator_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoCapture',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(max_length=80)),
                ('agent_id', models.CharField(max_length=80)),
                ('memo_id', models.CharField(blank=True, default='', max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sprout',
            fields=[
                ('id', models.CharField(default=memos.sprout_models.new_sprout_id, max_length=32, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(max_length=80)),
                ('sources', models.JSONField(default=list)),
                ('direction', models.CharField(blank=True, default='', max_length=500)),
                ('model_id', models.CharField(blank=True, default='', max_length=40)),
                ('result', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('article_id', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SproutJob',
            fields=[
                ('sprout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='memos.sprout')),
                ('tools', models.JSONField(default=list)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('stage', models.CharField(default='等待开始', max_length=80)),
                ('error', models.CharField(blank=True, default='', max_length=200)),
                ('token', models.CharField(blank=True, default='', max_length=32)),
                ('expires_at', models.DateTimeField(null=True)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
    ]
