# Generated by Django 5.2.17 on 2026-10-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0004_memocapture_sprout_sproutjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoCaptureAuthorization',
            fields=[
                ('task_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
