# Generated by Django 5.2.9 on 2026-04-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_table_comment_alter_article_article_id_and_more'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='readstat',
            table_comment='阅读统计表',
        ),
        migrations.AlterField(
            model_name='readstat',
            name='article',
            field=models.ForeignKey(db_comment='关联文章ID', help_text='关联的文章', on_delete=django.db.models.deletion.CASCADE, related_name='read_stats', to='article.article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='readstat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='记录时间', verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='readstat',
            name='duration',
            field=models.PositiveIntegerField(db_comment='该次访问的停留时长', default=0, help_text='该次访问的停留时长', verbose_name='阅读时长(秒)'),
        ),
        migrations.AlterField(
            model_name='readstat',
            name='id',
            field=models.BigAutoField(db_comment='阅读统计ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='readstat',
            name='user_identifier',
            field=models.CharField(db_comment='登录用户ID或游客IP', db_index=True, help_text='登录用户ID或游客IP', max_length=64, verbose_name='用户标识'),
        ),
    ]
