# Generated by Django 5.2.9 on 2026-04-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_table_comment_alter_article_article_id_and_more'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='asset',
            table_comment='资源表',
        ),
        migrations.AlterField(
            model_name='asset',
            name='file_extension',
            field=models.CharField(db_comment='文件扩展名', max_length=10, verbose_name='文件扩展名'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file_hash',
            field=models.CharField(db_comment='文件哈希值', db_index=True, max_length=64, verbose_name='文件哈希值'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file_path',
            field=models.CharField(db_comment='文件存储路径', max_length=500, verbose_name='文件存储路径'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file_size',
            field=models.BigIntegerField(db_comment='文件大小(字节)', verbose_name='文件大小(字节)'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file_type',
            field=models.CharField(choices=[('document', '文档'), ('image', '图片'), ('audio', '音频'), ('video', '视频'), ('archive', '压缩包'), ('code', '代码'), ('other', '其他')], db_comment='文件类型', max_length=20, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.CharField(db_comment='资源ID', max_length=32, primary_key=True, serialize=False, verbose_name='资源ID'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_linked',
            field=models.BooleanField(db_comment='是否已关联', default=False, verbose_name='是否已关联'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_valid',
            field=models.BooleanField(db_comment='是否有效', default=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='linked_article',
            field=models.ForeignKey(blank=True, db_comment='关联文章ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.article', verbose_name='关联文章'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='metadata',
            field=models.JSONField(blank=True, db_comment='文件元数据', default=dict, verbose_name='文件元数据'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='mime_type',
            field=models.CharField(db_comment='MIME类型', max_length=100, verbose_name='MIME类型'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(db_comment='文件名', max_length=255, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='original_name',
            field=models.CharField(db_comment='原始文件名', max_length=255, verbose_name='原始文件名'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='source_type',
            field=models.CharField(choices=[('attachment', '附件'), ('content', '内容'), ('other', '其他')], db_comment='资源来源类型', default='other', max_length=20, verbose_name='资源来源类型'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, db_comment='上传时间', verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='uploader',
            field=models.CharField(db_comment='上传者', default='admin', max_length=50, verbose_name='上传者'),
        ),
    ]
