# Generated by Codex on 2026-04-26

from django.db import migrations, models


def mark_gallery_image_assets(apps, schema_editor):
    Asset = apps.get_model('assets', 'Asset')
    Image = apps.get_model('article', 'Image')
    prefix = '/api/resource/view/'

    resource_ids = []
    for image_url in Image.objects.filter(image_url__startswith=prefix).values_list('image_url', flat=True):
        resource_id = image_url[len(prefix):].strip('/')
        if resource_id:
            resource_ids.append(resource_id)

    if resource_ids:
        Asset.objects.filter(id__in=resource_ids, source_type='other').update(source_type='image')


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_image_country_city'),
        ('assets', '0002_alter_asset_table_comment_alter_asset_file_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='source_type',
            field=models.CharField(
                choices=[
                    ('attachment', '附件'),
                    ('content', '内容'),
                    ('image', '图片文集'),
                    ('other', '其他'),
                ],
                db_comment='资源来源类型',
                default='other',
                max_length=20,
                verbose_name='资源来源类型',
            ),
        ),
        migrations.RunPython(mark_gallery_image_assets, migrations.RunPython.noop),
    ]
