import {useState} from 'react';
import EquipmentPreview from './EquipmentPreview';
import type {CombatEquipment, CombatCatalog, CombatProfile} from '../../types/api/combat';
import EquipmentCard from './EquipmentCard';
import ExplorationPreparation from './ExplorationPreparation';
import {slotLabels, statLabels, effectText} from './presentation';
import type {useCombatActions} from '../../hooks/useCombatActions';
import type {CombatSnapshot} from '../../types/api/combat';
export default function CombatProfilePanel({profile, catalog, actions, onObserve}: {profile: CombatProfile; catalog: CombatCatalog; actions: ReturnType<typeof useCombatActions>; onObserve: (id: string) => void}) {
    const [preview,setPreview] = useState<{item: CombatEquipment; remove?: boolean} | null>(null);
    const job = catalog.tables.professions.find(row => row.id === profile.progression.job);
    const busy = actions.busy || Boolean(profile.activeExplorationId);
    return <div className="scrollbar-hide h-full overflow-y-auto space-y-4 pr-1">
        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs text-orange-700">冒险档案</p><h3 className="mt-1 text-lg font-bold">Lv.{profile.progression.level} · {job?.name || '新手'}</h3><p className="mt-1 text-xs text-slate-500">经验 {profile.progression.experience} · HP {profile.hp} / {profile.attributes.hpMax} · MP {profile.mp} / {profile.attributes.mpMax}</p></div>{profile.activeExplorationId && <button onClick={() => onObserve(profile.activeExplorationId!)} className="rounded-full bg-orange-500 px-4 py-2 text-sm font-semibold text-white">观察当前探索</button>}</div>
            <dl className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{Object.entries(profile.attributes).filter(([key]) => statLabels[key]).map(([key,value]) => <div key={key} className="rounded-xl bg-slate-50 p-3 text-xs"><dt className="text-slate-500">{statLabels[key]}</dt><dd className="mt-1 font-semibold">{['accuracy','evasion','critical','criticalDamage'].includes(key) ? `${(Number(value)*100).toFixed(1)}%` : value}</dd></div>)}</dl>
        </section>
        {profile.promotionOptions.length > 0 && <section className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="text-sm font-medium">已达到转职等级，居民会在探索返回后选择分支。</p><p className="mt-1 text-xs text-slate-500">可选：{profile.promotionOptions.map(row => row.name).join('、')}</p></section>}
        <ExplorationPreparation key={profile.actorId} catalog={catalog} profile={profile} busy={actions.busy} onStart={constraints => {void actions.act<CombatSnapshot>({operation:'prepare', constraints}).then(run => {if (run) onObserve(run.id);});}}/>
        <section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-semibold">六槽穿戴</h3><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{Object.entries(slotLabels).map(([slot,label]) => <div key={slot} className="rounded-xl bg-slate-50 p-3 text-xs"><p className="text-slate-500">{label}</p><p className="mt-1 font-medium">{profile.equipment.find(r => r.id === profile.loadout[slot])?.snapshot.name || '空槽'}</p></div>)}</div></section>
        <section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-semibold">战斗技能 · 自动学习</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{profile.skills.map(skill => <article key={skill.id} className="rounded-xl bg-slate-50 p-3 text-xs"><strong>{skill.name} · {skill.rank} 级</strong><p className="mt-1 text-slate-500">{skill.kind === 'passive' ? '被动生效' : `消耗 ${skill.parameters.currentCost} MP · 冷却 ${skill.parameters.cooldownRounds} 回合`}</p><p className="mt-1 text-slate-500">{skill.effects.map(effectText).join(' · ')}</p></article>)}</div>{!profile.skills.length && <p className="mt-3 text-xs text-slate-500">新手没有技能，10 级一转后自动学习。</p>}</section>
        <section><h3 className="mb-3 font-semibold">装备背包</h3><div className="grid gap-3 sm:grid-cols-2">{profile.equipment.map(item => <EquipmentCard key={item.id} item={item} disabled={busy} worn={Object.values(profile.loadout).includes(item.id)} onEquip={() => setPreview({item})} onUnequip={() => setPreview({item,remove:true})} onFavorite={() => void actions.act({operation:'favorite', equipmentId:item.id, locked:!item.locked})} onSell={() => void actions.trade({kind:'sell_combat_equipment', equipmentId:item.id})}/>)}</div></section>
        <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">补给与商店回收</h3><button onClick={() => void actions.finishMarket()} disabled={actions.busy} className="text-xs text-orange-700">结束市场会话</button></div><p className="mt-1 text-xs text-slate-500">同一市场会话多次交易只扣一次入场体力；补给完成后结束会话再出发。</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{profile.potions.filter(r => Number(r.requiredLevel) <= profile.progression.level).map(row => <div key={row.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-xs"><span>{row.name} · 库存 {row.owned} · ¥{row.purchasePrice}</span><button disabled={busy} onClick={() => void actions.trade({kind:'buy_potion', potionId:row.id, quantity:1})} className="text-orange-700">购买一瓶</button></div>)}{profile.materials.filter(r => r.owned > 0).map(row => <div key={row.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-xs"><span>{row.name} ×{row.owned} · ¥{row.salePrice}/个</span><button disabled={busy} onClick={() => void actions.trade({kind:'sell_combat_material', materialId:row.id, quantity:Math.min(99,row.owned)})} className="text-orange-700">出售</button></div>)}</div></section>
        {preview && <EquipmentPreview key={preview.item.id} profile={profile} item={preview.item} remove={preview.remove} busy={actions.busy} onClose={() => setPreview(null)} onConfirm={() => {void actions.act({operation:'equip',equipment:{[preview.item.snapshot.slot]:preview.remove ? null : preview.item.id}}).then(result => {if (result) setPreview(null);});}}/>}
    </div>;
}
