# Generated by Django 5.2.9 on 2025-12-05 17:30

import anthology.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anthology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coll_id', models.CharField(default=anthology.models.generate_coll_id, max_length=32, unique=True, verbose_name='文集唯一标识')),
                ('title', models.CharField(max_length=20, verbose_name='文集名称')),
                ('description', models.CharField(default='暂无简介', max_length=100, verbose_name='文集简介')),
                ('icon_id', models.CharField(default='book', max_length=20, verbose_name='图标ID')),
                ('userid', models.CharField(default='admin', max_length=50, verbose_name='创建者ID')),
                ('permission', models.CharField(choices=[('public', '公开文集'), ('private', '私密文集')], default='public', max_length=10, verbose_name='访问权限')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('count', models.IntegerField(default=0, verbose_name='文章数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文集',
                'verbose_name_plural': '文集管理',
                'db_table': 'anthology',
                'ordering': ['-is_top', '-updated_at'],
                'unique_together': {('userid', 'title')},
            },
        ),
    ]
