# Generated by Django 5.2.9 on 2025-12-05 06:43

import anthology.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthology',
            name='coll_id',
            field=models.CharField(default=anthology.models.generate_coll_id, max_length=32, unique=True, verbose_name='文集唯一标识'),
        ),
    ]
