# Generated by Django 5.2.9 on 2026-04-23 12:55

import utils.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthology', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'anthology'
                      AND column_name = 'userid'
                ) THEN
                    ALTER TABLE anthology RENAME COLUMN userid TO user_id;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterModelTableComment(
            name='anthology',
            table_comment='文集表',
        ),
        migrations.AlterField(
            model_name='anthology',
            name='coll_id',
            field=models.CharField(db_comment='文集唯一标识', default=utils.id_generator.generate_coll_id, max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='文集唯一标识'),
        ),
        migrations.AlterField(
            model_name='anthology',
            name='count',
            field=models.IntegerField(db_comment='文章数量', default=0, verbose_name='文章数量'),
        ),
        migrations.AlterField(
            model_name='anthology',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='anthology',
            name='description',
            field=models.CharField(db_comment='文集简介', default='暂无简介', max_length=100, verbose_name='文集简介'),
        ),
        migrations.AlterField(
            model_name='anthology',
            name='icon_id',
            field=models.CharField(db_comment='图标ID', default='book', max_length=20, verbose_name='图标ID'),
        ),
        migrations.AlterField(
            model_name='anthology',
            name='is_top',
            field=models.BooleanField(db_comment='是否置顶', default=False, verbose_name='是否置顶'),
        ),
        migrations.AlterField(
            model_name='anthology',
            name='is_valid',
            field=models.BooleanField(db_comment='是否有效', default=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='anthology',
            name='permission',
            field=models.CharField(choices=[('public', '公开文集'), ('private', '私密文集')], db_comment='访问权限', default='public', max_length=10, verbose_name='访问权限'),
        ),
        migrations.AlterField(
            model_name='anthology',
            name='rag_not_synced_count',
            field=models.IntegerField(db_comment='未同步RAG文章数量', default=0, verbose_name='未同步RAG文章数量'),
        ),
        migrations.AlterField(
            model_name='anthology',
            name='sort',
            field=models.IntegerField(db_comment='排序值，值越小越靠前', default=0, verbose_name='排序值，值越小越靠前'),
        ),
        migrations.AlterField(
            model_name='anthology',
            name='title',
            field=models.CharField(db_comment='文集名称', max_length=20, verbose_name='文集名称'),
        ),
        migrations.AlterField(
            model_name='anthology',
            name='type',
            field=models.CharField(choices=[('article', '文章文集'), ('image', '图片文集')], db_comment='文集类型', default='article', max_length=10, verbose_name='文集类型'),
        ),
        migrations.AlterField(
            model_name='anthology',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='anthology',
            name='user_id',
            field=models.CharField(db_comment='创建者ID', default='admin', max_length=50, verbose_name='创建者ID'),
        ),
        migrations.AlterModelTable(
            name='anthology',
            table='anthologies',
        ),
    ]
