# Generated by Django 5.2.17 on 2026-10-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthology', '0007_book_collection_and_reading_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthology',
            name='type',
            field=models.CharField(choices=[('article', '文章文集'), ('image', '图片文集'), ('agent', 'Agent 文集'), ('book', '图书文集'), ('learning', '学习文集')], db_comment='文集类型', default='article', max_length=10, verbose_name='文集类型'),
        ),
    ]
