import {ChevronLeft, ChevronRight} from 'lucide-react';
import type {ReadingGraph, ReadingNode, SourceEvidence} from '../../types/bookAnalysis';
import {nodeLabels, relationLabels} from '../../utils/readingGraph';
import PersonBasics from './PersonBasics';

interface Props {node: ReadingNode; neighbors: ReadingGraph; page: number; onPage: (page: number) => void; onSelect: (id: string) => void; onRead: (source: SourceEvidence) => void}
export default function ReadingNodeDetails({node, neighbors, page, onPage, onSelect, onRead}: Props) {
    const related = neighbors.edges.filter(edge => edge.source === node.id || edge.target === node.id);
    const relationships = node.kind === 'person' ? related.filter(edge => neighbors.nodes.find(n => n.id === (edge.source === node.id ? edge.target : edge.source))?.kind === 'person') : related;
    return <>
        {node.kind === 'person' ? <PersonBasics node={node}/> : <section className="rounded-xl border border-slate-200 bg-slate-50/40 p-3"><h3 className="mb-2 text-xs font-semibold text-slate-800">基本说明</h3><p className="text-xs leading-6 text-slate-600">{node.facts[0]?.description || '暂无说明。'}</p>{!!node.aliases.length && <p className="mt-2 text-[11px] text-slate-400">别名：{node.aliases.join('、')}</p>}{node.timeLabel && <p className="mt-2 text-[11px] text-slate-500">故事时间：{node.timeLabel}{!node.timeOrder && '（无明确日期）'}</p>}</section>}
        <section><h3 className="mb-3 text-xs font-semibold text-slate-800">{node.kind === 'person' ? '人物关系与变化' : '关系与变化'} <span className="ml-1 text-[10px] font-normal text-slate-400">{relationships.length}</span></h3><div className="max-h-56 space-y-2 overflow-y-auto overscroll-contain">{relationships.length ? relationships.map(edge => {
            const otherId = edge.source === node.id ? edge.target : edge.source;
            const other = neighbors.nodes.find(n => n.id === otherId);
            return <div key={edge.id} className="rounded-lg border border-slate-100 bg-slate-50/50 p-3 text-xs leading-5"><p className="text-slate-600">{edge.source === node.id ? node.name : other?.name || '关联对象'} <span className="mx-1 text-slate-400">— {relationLabels[edge.kind] || edge.label} →</span> {edge.target === node.id ? node.name : other?.name || '关联对象'}</p>{edge.label && edge.label !== edge.kind && edge.label !== relationLabels[edge.kind] && <p className="mt-1 text-[11px] text-slate-500">{edge.label}</p>}<p className="mt-1 text-[10px] text-slate-400">{edge.context.chapterTitle} {edge.context.timeLabel} {edge.context.state} · {edge.origin === 'user' ? '用户补充' : edge.origin === 'derived' ? '展示关联' : '原文关系'}</p><div className="mt-2 flex flex-wrap gap-2">{other && <button onClick={() => onSelect(otherId)} className="text-[11px] text-orange-600">查看 {other.name}</button>}{edge.evidence.map((source, index) => <button key={index} onClick={() => onRead(source)} className="text-[10px] text-slate-400 hover:text-orange-600">关系证据</button>)}</div></div>;
        }) : <p className="text-xs leading-6 text-slate-400">当前没有明确的{node.kind === 'person' ? '人物关系' : '关系'}记录。</p>}</div></section>
        <section className="border-t border-slate-100 pt-4"><h3 className="mb-2 text-xs font-semibold text-slate-800">关联内容</h3><div>{Object.entries(nodeLabels).map(([kind, label]) => {
            const items = neighbors.nodes.filter(n => n.kind === kind && n.id !== node.id);
            return items.length ? <div key={kind} className="mb-3"><p className="mb-1.5 text-[10px] text-slate-400">{label} · {items.length}</p><div className="flex flex-wrap gap-1.5">{items.map(n => <button key={n.id} onClick={() => onSelect(n.id)} className="max-w-full rounded-md border border-slate-200 px-2 py-1 text-left text-xs text-slate-600 hover:border-orange-200 hover:text-orange-600">{n.name}</button>)}</div></div> : null;
        })}{!neighbors.nodes.some(n => n.id !== node.id) && <p className="text-xs text-slate-400">暂无关联对象。</p>}</div></section>
        {!!node.hypotheses?.length && <section className="border-t border-slate-100 pt-4"><h3 className="mb-2 text-xs font-semibold text-slate-800">待验证线索与解读</h3><div className="space-y-2">{node.hypotheses.map(item => <div key={item.id} className="rounded-lg border border-purple-100 bg-purple-50/50 p-3"><span className="text-[9px] text-purple-600">{item.state === 'pending' ? '待验证' : item.state === 'confirmed' ? '已确认' : item.state === 'refuted' ? '已推翻' : '有争议'} · {item.chapterTitle}</span><p className="mt-1 text-xs leading-6 text-slate-600">{item.description}</p></div>)}</div></section>}
        <section className="border-t border-slate-100 pt-4"><h3 className="mb-3 text-xs font-semibold text-slate-800">原文证据与记录 <span className="ml-1 text-[10px] font-normal text-slate-400">{node.factTotal || node.facts.length}</span></h3><div className="max-h-72 space-y-4 overflow-y-auto overscroll-contain">{node.facts.map((fact, index) => <div key={index} className="rounded-lg border border-slate-100 p-3"><span className={`rounded px-1.5 py-0.5 text-[10px] ${fact.status === 'explicit' ? 'bg-slate-100 text-slate-500' : 'bg-amber-50 text-amber-700'}`}>{fact.status === 'explicit' ? '原文明示' : fact.status === 'user' ? '用户修正' : 'AI 推断'}</span><p className="mt-2 whitespace-pre-wrap text-xs leading-6 text-slate-600">{fact.description}</p>{fact.evidence && <div className="mt-2 rounded-lg bg-slate-50 p-3"><p className="text-[11px] leading-6 text-slate-500">“{fact.evidence.quote}”</p><button onClick={() => onRead(fact.evidence!)} className="mt-2 text-[11px] text-orange-600">{fact.evidence.chapterTitle} · 查看原文</button></div>}</div>)}</div>{(node.factTotal || 0) > 50 && <div className="mt-3 flex items-center justify-between text-xs text-slate-500"><button aria-label="上一页人物记录" disabled={page === 1} onClick={() => onPage(page - 1)}><ChevronLeft className="h-4 w-4"/></button>{page} / {Math.ceil((node.factTotal || 0) / 50)}<button aria-label="下一页人物记录" disabled={page * 50 >= (node.factTotal || 0)} onClick={() => onPage(page + 1)}><ChevronRight className="h-4 w-4"/></button></div>}</section>
    </>;
}
