import {useCallback, useEffect, useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {ArchiveRestore, Filter, FolderCog, Plus, Search, Sparkles, Trash2} from 'lucide-react';
import {createPromptTemplate, getPromptTaxonomy, getPromptTemplate, getPromptTemplates, getPromptTrash, purgePromptTemplate, purgePromptUsage, restorePromptTemplate, restorePromptUsage, updatePromptTemplate} from '../api/prompt';
import type {PromptFilters, PromptTaxonomies, PromptTemplate, PromptTemplateInput, PromptTrash} from '../types/api/prompt';
import {useToast} from '../components/common/ToastProvider';
import PromptCard from '../components/PromptLibrary/PromptCard';
import PromptDetailDrawer from '../components/PromptLibrary/PromptDetailDrawer';
import PromptTemplateModal from '../components/PromptLibrary/PromptTemplateModal';
import PromptTaxonomyModal from '../components/PromptLibrary/PromptTaxonomyModal';

const emptyTaxonomies: PromptTaxonomies = {categories: [], themes: [], tags: []};

export default function PromptLibraryPage() {
  const toast = useToast();
  const [searchParams, setSearchParams] = useSearchParams();
  const [items, setItems] = useState<PromptTemplate[]>([]);
  const [taxonomies, setTaxonomies] = useState<PromptTaxonomies>(emptyTaxonomies);
  const [filters, setFilters] = useState<PromptFilters>({ordering: 'updated'});
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<PromptTemplate | null>(null);
  const [editing, setEditing] = useState<PromptTemplate | null | undefined>(undefined);
  const [taxonomyOpen, setTaxonomyOpen] = useState(false);
  const [trash, setTrash] = useState<PromptTrash | null>(null);
  const refresh = useCallback(async () => { setLoading(true); try { const [response, taxonomy] = await Promise.all([getPromptTemplates(filters), getPromptTaxonomy()]); setItems(response.list); setTaxonomies(taxonomy); } catch (error) { toast.error((error as Error).message || '加载提示词库失败'); } finally { setLoading(false); } }, [filters, toast]);
  useEffect(() => { void refresh(); }, [refresh]);
  const open = async (item: PromptTemplate) => { try { setSelected(await getPromptTemplate(item.id)); } catch (error) { toast.error((error as Error).message || '打开提示词失败'); } };
  useEffect(() => {
    const promptId = searchParams.get('promptId');
    if (!promptId) return;
    void getPromptTemplate(promptId).then(setSelected).catch(() => toast.error('未找到该提示词')).finally(() => setSearchParams({}, {replace: true}));
  }, [searchParams, setSearchParams, toast]);
  const save = async (data: PromptTemplateInput) => { try { const saved = editing ? await updatePromptTemplate(editing.id, data) : await createPromptTemplate(data); toast.success(editing ? '模板已更新' : '模板已创建'); setEditing(undefined); await refresh(); if (selected?.id === saved.id) setSelected(await getPromptTemplate(saved.id)); } catch (error) { toast.error((error as Error).message || '保存失败'); throw error; } };
  const toggleFavorite = async (item: PromptTemplate) => { try { await updatePromptTemplate(item.id, {isFavorite: !item.isFavorite}); await refresh(); } catch (error) { toast.error((error as Error).message || '更新收藏失败'); } };
  const showTrash = async () => { try { setTrash(await getPromptTrash()); } catch (error) { toast.error((error as Error).message || '加载回收站失败'); } };
  const restore = async (id: string) => { await restorePromptTemplate(id); toast.success('提示词已恢复'); setTrash(await getPromptTrash()); await refresh(); };
  const restoreUsage = async (id: string) => { await restorePromptUsage(id); toast.success('效果记录已恢复'); setTrash(await getPromptTrash()); await refresh(); };
  const purgeTemplate = async (id: string) => { if (!window.confirm('彻底删除模板及其已删除效果记录？仅未被其他内容使用的提示词图片会一并清理。')) return; await purgePromptTemplate(id); setTrash(await getPromptTrash()); toast.success('已彻底删除'); };
  const purgeUsage = async (id: string) => { if (!window.confirm('彻底删除这条效果记录？未被其他内容使用的提示词图片会一并清理。')) return; await purgePromptUsage(id); setTrash(await getPromptTrash()); toast.success('已彻底删除'); };
  return <main className="mx-auto min-h-[calc(100vh-64px)] max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
    <header className="relative overflow-hidden rounded-2xl border border-orange-100 bg-white px-5 py-5 shadow-sm sm:px-7"><div className="absolute -right-12 -top-16 h-44 w-44 rounded-full bg-orange-100/70 blur-3xl"/><div className="relative flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-bold tracking-[0.18em] text-orange-600">PROMPT CABINET</p><h1 className="mt-1 flex items-center gap-2 text-2xl font-bold text-slate-900"><Sparkles className="h-6 w-6 text-orange-500"/>提示词库</h1><p className="mt-1 text-sm text-slate-500">把好用的表达、动态字段和满意的效果，一起收好。</p></div><div className="flex flex-wrap gap-2"><button onClick={() => setTaxonomyOpen(true)} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-600 hover:border-orange-200"><FolderCog className="h-4 w-4"/>分类与标签</button><button onClick={() => void showTrash()} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-600 hover:border-orange-200"><Trash2 className="h-4 w-4"/>回收站</button><button onClick={() => setEditing(null)} className="inline-flex items-center gap-1.5 rounded-lg bg-orange-500 px-3 py-2 text-xs font-semibold text-white shadow-sm shadow-orange-500/20 hover:bg-orange-600"><Plus className="h-4 w-4"/>新建提示词</button></div></div></header>
    <section className="mt-5 rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row"><div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={filters.keyword || ''} onChange={event => setFilters({...filters, keyword: event.target.value})} placeholder="搜索标题、提示词、分类或标签…" className="w-full rounded-lg bg-slate-50 py-2 pl-9 pr-3 text-sm outline-none ring-orange-500/20 focus:bg-white focus:ring-2"/></div><div className="flex flex-wrap gap-2"><select value={filters.type || ''} onChange={event => setFilters({...filters, type: (event.target.value || undefined) as PromptFilters['type']})} className="rounded-lg border border-slate-200 px-2 py-2 text-xs"><option value="">全部类型</option><option value="image">生图</option><option value="html_report">HTML 报告</option><option value="general">通用</option></select><select value={filters.categoryId || ''} onChange={event => setFilters({...filters, categoryId: event.target.value || undefined})} className="rounded-lg border border-slate-200 px-2 py-2 text-xs"><option value="">全部分类</option>{taxonomies.categories.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button onClick={() => setFilters({...filters, favorite: !filters.favorite})} className={`rounded-lg border px-2.5 py-2 text-xs ${filters.favorite ? 'border-orange-200 bg-orange-50 text-orange-700' : 'border-slate-200 text-slate-500'}`}><Filter className="mr-1 inline h-3.5 w-3.5"/>收藏</button></div></div><div className="mt-3 flex flex-wrap gap-1.5 text-xs"><span className="pt-1 text-slate-400">主题</span>{taxonomies.themes.map(item => <button key={item.id} onClick={() => setFilters(current => ({...current, themeIds: current.themeIds?.includes(item.id) ? current.themeIds.filter(id => id !== item.id) : [...(current.themeIds || []), item.id]}))} className={`rounded-full px-2 py-1 ${filters.themeIds?.includes(item.id) ? 'bg-violet-100 text-violet-700' : 'bg-slate-100 text-slate-500'}`}>{item.name}</button>)}<span className="ml-2 pt-1 text-slate-400">标签</span>{taxonomies.tags.map(item => <button key={item.id} onClick={() => setFilters(current => ({...current, tagIds: current.tagIds?.includes(item.id) ? current.tagIds.filter(id => id !== item.id) : [...(current.tagIds || []), item.id]}))} className={`rounded-full px-2 py-1 ${filters.tagIds?.includes(item.id) ? 'bg-orange-100 text-orange-700' : 'bg-slate-100 text-slate-500'}`}>{item.name}</button>)}</div></section>
    <section className="mt-5">{loading ? <div className="py-24 text-center text-sm text-slate-400">正在整理你的提示词…</div> : items.length ? <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map(item => <PromptCard key={item.id} item={item} onOpen={() => void open(item)} onToggleFavorite={() => void toggleFavorite(item)}/>)}</div> : <div className="rounded-2xl border border-dashed border-orange-200 bg-white py-24 text-center"><Sparkles className="mx-auto h-10 w-10 text-orange-300"/><h2 className="mt-3 text-sm font-bold text-slate-700">先收下第一条好提示词</h2><p className="mt-1 text-xs text-slate-500">配置动态字段后，每次只填内容就能直接复制使用。</p><button onClick={() => setEditing(null)} className="mt-4 rounded-lg bg-orange-500 px-3 py-2 text-xs font-semibold text-white">新建提示词</button></div>}</section>
    <PromptTemplateModal key={editing?.id || (editing === null ? 'new' : 'closed')} open={editing !== undefined} template={editing || null} taxonomies={taxonomies} onClose={() => setEditing(undefined)} onSave={save}/>
    <PromptTaxonomyModal open={taxonomyOpen} taxonomies={taxonomies} onClose={() => setTaxonomyOpen(false)} onChanged={() => void refresh()}/>
    <PromptDetailDrawer template={selected} onClose={() => setSelected(null)} onChanged={() => { if (selected) void open(selected); void refresh(); }}/>
    {trash && <div className="fixed inset-0 z-[121] flex items-center justify-center p-4"><div className="absolute inset-0 bg-slate-900/40" onClick={() => setTrash(null)}/><section className="relative w-full max-w-2xl rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="text-lg font-bold text-slate-900">提示词回收站</h2><p className="mt-1 text-xs text-slate-500">恢复不会删除图片；彻底删除时，只清理未被其他内容引用的提示词图片。</p></div><button onClick={() => setTrash(null)} className="text-slate-400">×</button></header><div className="max-h-[60vh] space-y-5 overflow-y-auto p-4"><div><p className="mb-2 text-xs font-bold text-slate-500">模板</p>{trash.templates.map(item => <div key={item.id} className="mb-2 flex items-center justify-between rounded-xl border border-slate-100 p-3"><div><p className="text-sm font-semibold text-slate-700">{item.title}</p><p className="text-xs text-slate-400">删除于 {item.deletedAt || '未知时间'}</p></div><div className="flex gap-2"><button onClick={() => void restore(item.id)} className="inline-flex items-center gap-1 rounded-lg bg-lime-50 px-3 py-2 text-xs font-semibold text-lime-700"><ArchiveRestore className="h-3.5 w-3.5"/>恢复</button><button onClick={() => void purgeTemplate(item.id)} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-semibold text-red-600">彻底删除</button></div></div>)}</div><div><p className="mb-2 text-xs font-bold text-slate-500">效果记录</p>{trash.usages.map(item => <div key={item.id} className="mb-2 flex items-center justify-between rounded-xl border border-slate-100 p-3"><div><p className="text-sm font-semibold text-slate-700">{item.modelName || '未命名效果记录'}</p><p className="text-xs text-slate-400">{item.resultImages.length} 张图片 · 删除于 {item.deletedAt || '未知时间'}</p></div><div className="flex gap-2"><button onClick={() => void restoreUsage(item.id)} className="rounded-lg bg-lime-50 px-3 py-2 text-xs font-semibold text-lime-700">恢复</button><button onClick={() => void purgeUsage(item.id)} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-semibold text-red-600">彻底删除</button></div></div>)}{!trash.templates.length && !trash.usages.length && <p className="py-10 text-center text-sm text-slate-400">回收站是空的。</p>}</div></div></section></div>}
  </main>;
}
