# Generated by Django 5.2.9 on 2026-04-23 12:55

import django.db.models.deletion
import django.utils.timezone
import utils.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        ('categories', '0002_alter_category_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='article',
            table_comment='文章表',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(db_comment='文章唯一标识', default=utils.id_generator.generate_article_id, editable=False, help_text='文章唯一标识', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(db_comment='文章作者', default='admin', help_text='文章作者', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, db_comment='文章所属分类ID', help_text='文章所属分类', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='categories.category', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='coll_id',
            field=models.CharField(db_comment='所属文集ID', help_text='所属文集ID，与anthologies表的coll_id对应', max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(db_comment='文章内容（Markdown格式）', help_text='文章内容（Markdown格式）'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(db_comment='创建时间', default=django.utils.timezone.now, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_polishing',
            field=models.BooleanField(db_comment='是否正在进行AI润色', default=False, help_text='是否正在进行AI润色'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_rag_synced',
            field=models.BooleanField(db_comment='是否已同步到RAG知识库', default=False, help_text='是否已同步到RAG知识库'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_valid',
            field=models.BooleanField(db_comment='是否有效', default=True, help_text='是否有效'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_rag_synced_at',
            field=models.DateTimeField(blank=True, db_comment='上次同步到RAG的时间', help_text='上次同步到RAG的时间', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, db_comment='父级文章ID', help_text='父级文章ID，用于构建文档树形结构', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='article.article', verbose_name='父级文章'),
        ),
        migrations.AlterField(
            model_name='article',
            name='permission',
            field=models.CharField(choices=[('public', '公开'), ('private', '私有')], db_comment='文章权限', default='public', help_text='文章权限', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_count',
            field=models.PositiveIntegerField(db_comment='阅读次数', default=0, help_text='阅读次数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_time',
            field=models.PositiveIntegerField(db_comment='预计阅读时长(分钟)', default=0, help_text='预计阅读时长(分钟)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sort',
            field=models.IntegerField(db_comment='文章排序值，值越小越靠前', default=0, help_text='文章排序值，值越小越靠前'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, db_comment='文章来源网址', help_text='文章来源网址', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_comment='文章标题', help_text='文章标题', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='total_read_seconds',
            field=models.PositiveIntegerField(db_comment='累计阅读时长(秒)', default=0, help_text='累计阅读时长(秒)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', help_text='更新时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='word_count',
            field=models.PositiveIntegerField(db_comment='文章字数', default=0, help_text='文章字数'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
