# Generated by Django 5.2.13 on 2026-06-15 12:21

import django.db.models.deletion
import utils.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_agent_post_rating_and_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='agent_post_category',
            field=models.CharField(blank=True, db_comment='Agent 帖子文集内分类', default='', help_text='Agent 帖子文集内分类', max_length=50),
        ),
        migrations.CreateModel(
            name='ArticlePostRating',
            fields=[
                ('rating_id', models.CharField(db_comment='帖子评分唯一标识', default=utils.id_generator.generate_article_post_rating_id, editable=False, help_text='帖子评分唯一标识', max_length=32, primary_key=True, serialize=False, unique=True)),
                ('rating', models.PositiveSmallIntegerField(db_comment='评分', help_text='评分，1-10 分')),
                ('rater_id', models.CharField(blank=True, db_comment='评分者标识', default='', max_length=80)),
                ('rater_name', models.CharField(blank=True, db_comment='评分者名称', default='', max_length=120)),
                ('rater_avatar', models.CharField(blank=True, db_comment='评分者头像', default='', max_length=500)),
                ('is_valid', models.BooleanField(db_comment='是否有效', default=True, help_text='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间', help_text='更新时间')),
                ('article', models.ForeignKey(db_comment='所属帖子ID', on_delete=django.db.models.deletion.CASCADE, related_name='post_ratings', to='article.article', verbose_name='所属帖子')),
            ],
            options={
                'verbose_name': 'Agent 帖子评分',
                'verbose_name_plural': 'Agent 帖子评分',
                'db_table': 'article_post_ratings',
                'db_table_comment': 'Agent 帖子评分表',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['article', 'is_valid'], name='article_pos_article_7a34dc_idx'), models.Index(fields=['rater_id'], name='article_pos_rater_i_2063d9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_valid', True)), fields=('article', 'rater_id'), name='uniq_valid_agent_post_rating_user')],
            },
        ),
    ]
