# Generated by Django 5.2.17 on 2026-09-25 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_article_version_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleversion',
            name='article',
            field=models.ForeignKey(db_column='article_id', db_comment='所属文章 ID', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='article.article', verbose_name='所属文章'),
        ),
    ]
