# Generated by Django 5.2.17 on 2026-09-27 02:42

import django.db.models.deletion
import utils.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_alter_articleversion_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageReview',
            fields=[
                ('review_id', models.CharField(db_comment='照片评价 ID', default=utils.id_generator.generate_image_review_id, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='评价 ID')),
                ('agent_key', models.CharField(db_comment='提交评价的 Agent ID', max_length=40, verbose_name='Agent 标识')),
                ('agent_name', models.CharField(db_comment='提交时的 Agent 名称', max_length=50, verbose_name='Agent 名称')),
                ('commentary', models.TextField(db_comment='评价正文', verbose_name='评语')),
                ('score_theme', models.DecimalField(db_comment='主题分，0 到 10，步进 0.5', decimal_places=1, max_digits=3, verbose_name='主题')),
                ('score_composition', models.DecimalField(db_comment='构图分，0 到 10，步进 0.5', decimal_places=1, max_digits=3, verbose_name='构图')),
                ('score_idea', models.DecimalField(db_comment='思想分，0 到 10，步进 0.5', decimal_places=1, max_digits=3, verbose_name='思想')),
                ('score_light', models.DecimalField(db_comment='光影分，0 到 10，步进 0.5', decimal_places=1, max_digits=3, verbose_name='光影')),
                ('score_color', models.DecimalField(db_comment='色彩分，0 到 10，步进 0.5', decimal_places=1, max_digits=3, verbose_name='色彩')),
                ('score_focus', models.DecimalField(db_comment='对焦分，0 到 10，步进 0.5', decimal_places=1, max_digits=3, verbose_name='对焦')),
                ('overall', models.DecimalField(db_comment='六项平均后对齐到 0.5', decimal_places=1, max_digits=3, verbose_name='综合分')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间')),
                ('image', models.ForeignKey(db_column='image_id', db_comment='所属照片 ID', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='article.image', verbose_name='照片')),
            ],
            options={
                'verbose_name': '照片评价',
                'verbose_name_plural': '照片评价',
                'db_table': 'image_reviews',
                'db_table_comment': '照片评价表',
                'ordering': ['updated_at', 'review_id'],
                'constraints': [models.UniqueConstraint(fields=('image', 'agent_key'), name='uniq_image_review_agent')],
            },
        ),
    ]
