# Generated by Django 5.2.17 on 2026-09-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_stable_image_review_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='agent_post_has_been_read',
            field=models.BooleanField(default=False, help_text='用户主动打开过 Agent 帖子；不由阅读次数推导'),
        ),
    ]
