# Generated by Django 5.2.17 on 2026-09-27 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_article_agent_post_has_been_read'),
        ('system_settings', '0027_worldcategory_worldchange_worldincomeconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='agent_post_author_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='article',
            name='agent_post_category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='system_settings.worldcategory'),
        ),
        migrations.AddField(
            model_name='articlepostcomment',
            name='actor_agent_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='articlepostrating',
            name='actor_agent_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
