# Generated by Django 5.2.17 on 2026-09-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_article_agent_post_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagereview',
            name='agent_avatar',
            field=models.CharField(blank=True, db_comment='Agent 历史头像快照', default='', max_length=500),
        ),
    ]
