# Generated by Django 5.2.17 on 2026-09-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_imagereview_agent_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepostcomment',
            name='parent_comment_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='articlepostcomment',
            name='reply_to_actor_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='articlepostcomment',
            name='root_comment_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
