import {useEffect, useRef, useState} from 'react';
import {createPortal} from 'react-dom';
import {useEscapeDismissal} from '../../hooks/useEscapeDismissal';
import {farmAtlasUrl} from './assets';
import {X} from 'lucide-react';
import {Select} from '../common/Select';
import {getFarmRules,saveFarmAppearance,saveFarmRules} from '../../api/farm';
import type {FarmState,FarmRules} from '../../types/api/farm';

export function FarmConfiguration({farm,onClose,onSaved}:{farm:FarmState;onClose:()=>void;onSaved:()=>void}) {
    const [appearance,setAppearance]=useState(farm.appearance),[rules,setRules]=useState<FarmRules|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);
    const modal=useRef<HTMLDivElement>(null);
    useEscapeDismissal(true,()=>{if(!saving)onClose();return true;});
    useEffect(()=>{let alive=true;getFarmRules().then(r=>{if(alive)setRules(r);}).catch(()=>{if(alive)setError('经营目录加载失败，请关闭后重试');});const previous=document.activeElement as HTMLElement|null;modal.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Tab'){const items=modal.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input, [tabindex="0"]');if(items?.length){const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}};document.addEventListener('keydown',key);return()=>{alive=false;document.removeEventListener('keydown',key);previous?.focus();};},[onClose]);
    async function save(){if(!rules)return;setSaving(true);setError('');try{await saveFarmRules(rules);await saveFarmAppearance(farm.id,appearance);onSaved();onClose();}catch{setError('保存失败，请检查数值或重试；已经保存的目录仍然有效');}finally{setSaving(false);}}
    const number=(label:string,value:number,onChange:(n:number)=>void)=><label key={label} className="block text-xs text-slate-500">{label}<input type="number" min={1} max={1000000} value={value} onChange={e=>onChange(Number(e.target.value))} className="mt-1 w-full rounded-lg border border-slate-200 px-2 py-2 text-sm text-slate-700"/></label>;
    return createPortal(<div className="fixed inset-0 z-[140] flex items-center justify-center bg-slate-900/35 p-3" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)onClose();}}><div ref={modal} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="farm-config-title" className="flex max-h-[90vh] w-full max-w-2xl flex-col rounded-2xl bg-white shadow-xl">
        <div className="flex items-center justify-between border-b border-slate-100 p-5"><h2 id="farm-config-title" className="font-bold text-slate-800">农场配置</h2><button aria-label="关闭配置" onClick={onClose} disabled={saving}><X className="h-5 w-5 text-slate-400"/></button></div>
        <div className="overflow-y-auto p-5"><h3 className="text-sm font-semibold text-slate-700">{farm.actorName}的像素形象</h3><div className="mt-3 grid grid-cols-2 gap-4"><Select menuPortal value={String(appearance.style)} options={['草帽园丁','长发居民','绿帽居民','短发居民'].map((label,i)=>({label,value:String(i)}))} onChange={value=>setAppearance({...appearance,style:Number(value)})}/><Select menuPortal value={String(appearance.palette)} options={['橘色','湖蓝','草绿','莓紫'].map((label,i)=>({label,value:String(i)}))} onChange={value=>setAppearance({...appearance,palette:Number(value)})}/></div>
        <div className="mt-3 flex justify-center rounded-xl bg-lime-50 p-3"><div aria-label="像素角色预览" style={{width:96,height:96,imageRendering:'pixelated',backgroundImage:`url(${farmAtlasUrl})`,backgroundSize:'3072px auto',backgroundPosition:`0px -${(appearance.style*8+appearance.palette*2)*192}px`}}/></div>
        <h3 className="mt-6 text-sm font-semibold text-slate-700">世界经营目录</h3><p className="mt-1 text-xs leading-5 text-slate-500">所有农场共用。更改只影响后续购买和新生产周期；正在成长的作物与动物周期保留原规则。作物规则请在物品图鉴中编辑。</p>
        {!rules?<p className="py-5 text-sm text-slate-400">加载目录中…</p>:<div className="mt-4 space-y-4">
        {Object.entries(rules.animals).map(([id,r])=><fieldset key={id} className="rounded-xl border border-slate-200 p-3"><legend className="px-1 text-xs font-semibold text-slate-700">{r.name}</legend><div className="grid grid-cols-3 gap-3">{(['periodSeconds','price','salePrice'] as const).map((field,i)=>number(['生产秒数','购买价','普通回收价'][i],r[field],n=>setRules({...rules,animals:{...rules.animals,[id]:{...r,[field]:n}}})))}</div></fieldset>)}
        {Object.entries(rules.buildings).map(([id,r])=><fieldset key={id} className="rounded-xl border border-slate-200 p-3"><legend className="px-1 text-xs font-semibold text-slate-700">{r.name}</legend><div className="grid grid-cols-3 gap-3">{r.prices.map((price,i)=><div key={i} className="space-y-2">{number(`${i+1}级费用`,price,n=>setRules({...rules,buildings:{...rules.buildings,[id]:{...r,prices:r.prices.map((v,j)=>j===i?n:v)}}}))}{number(`${i+1}级容量`,r.capacities[i],n=>setRules({...rules,buildings:{...rules.buildings,[id]:{...r,capacities:r.capacities.map((v,j)=>j===i?n:v)}}}))}</div>)}</div></fieldset>)}
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{number('每份饲料价格',rules.feedPrice,n=>setRules({...rules,feedPrice:n}))}{rules.landPrices.map((price,i)=><div key={i}>{number(`第${i+2}组土地价格`,price,n=>setRules({...rules,landPrices:rules.landPrices.map((v,j)=>j===i?n:v)}))}</div>)}</div></div>}
        {error&&<p role="alert" className="mt-4 text-sm text-red-600">{error}</p>}</div>
        <div className="flex justify-end gap-3 border-t border-slate-100 p-4"><button disabled={saving} onClick={onClose} className="rounded-lg px-4 py-2 text-sm text-slate-500">取消</button><button disabled={saving||!rules} onClick={()=>void save()} className="rounded-lg bg-orange-500 px-4 py-2 text-sm text-white disabled:opacity-50">{saving?'正在保存…':'保存配置'}</button></div>
    </div></div>,document.body);
}
