# Generated by Django 5.2.9 on 2026-04-23 12:55

import utils.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'categories'
                      AND column_name = 'userid'
                ) THEN
                    ALTER TABLE categories RENAME COLUMN userid TO user_id;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterModelTableComment(
            name='category',
            table_comment='分类表',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(db_comment='分类专属ID', default=utils.id_generator.generate_category_id, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='分类专属ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, db_comment='分类描述', default='', max_length=200, verbose_name='分类描述'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_key',
            field=models.CharField(db_comment='图标Key', default='Folder', max_length=50, verbose_name='图标Key'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_valid',
            field=models.BooleanField(db_comment='是否有效', default=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_comment='分类名称', max_length=50, unique=True, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort',
            field=models.IntegerField(db_comment='排序值，值越小越靠前', default=0, verbose_name='排序值，值越小越靠前'),
        ),
        migrations.AlterField(
            model_name='category',
            name='theme_id',
            field=models.CharField(db_comment='颜色主题ID', default='blue', max_length=20, verbose_name='颜色主题ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user_id',
            field=models.CharField(db_comment='创建者ID', default='admin', max_length=50, verbose_name='创建者ID'),
        ),
    ]
