# Generated by Django 5.2.9 on 2026-04-23 12:55

import utils.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'tags'
                      AND column_name = 'userid'
                ) THEN
                    ALTER TABLE tags RENAME COLUMN userid TO user_id;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterModelTableComment(
            name='tag',
            table_comment='标签表',
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_valid',
            field=models.BooleanField(db_comment='是否有效', default=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_comment='标签名称', max_length=30, verbose_name='标签名称'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sort',
            field=models.IntegerField(db_comment='排序值，值越小越靠前', default=0, verbose_name='排序值，值越小越靠前'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(db_comment='标签专属ID', default=utils.id_generator.generate_tag_id, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='标签专属ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='theme_id',
            field=models.CharField(db_comment='主题ID', default='blue', max_length=36, verbose_name='主题ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user_id',
            field=models.CharField(db_comment='创建者ID', default='admin', max_length=50, verbose_name='创建者ID'),
        ),
    ]
