# Generated by Django 5.2.9 on 2026-04-23 12:55

import utils.id_generator
from django.db import migrations, models


def rename_legacy_userid_column(apps, schema_editor):
    table_name = 'tags'
    old_column = 'userid'
    new_column = 'user_id'

    with schema_editor.connection.cursor() as cursor:
        try:
            description = schema_editor.connection.introspection.get_table_description(cursor, table_name)
        except Exception:
            return

        column_names = {column.name for column in description}
        if old_column not in column_names or new_column in column_names:
            return

        quoted_table = schema_editor.quote_name(table_name)
        quoted_old_column = schema_editor.quote_name(old_column)
        quoted_new_column = schema_editor.quote_name(new_column)
        schema_editor.execute(
            f'ALTER TABLE {quoted_table} RENAME COLUMN {quoted_old_column} TO {quoted_new_column}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rename_legacy_userid_column, migrations.RunPython.noop),
        migrations.AlterModelTableComment(
            name='tag',
            table_comment='标签表',
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_valid',
            field=models.BooleanField(db_comment='是否有效', default=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_comment='标签名称', max_length=30, verbose_name='标签名称'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sort',
            field=models.IntegerField(db_comment='排序值，值越小越靠前', default=0, verbose_name='排序值，值越小越靠前'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(db_comment='标签专属ID', default=utils.id_generator.generate_tag_id, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='标签专属ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='theme_id',
            field=models.CharField(db_comment='主题ID', default='blue', max_length=36, verbose_name='主题ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user_id',
            field=models.CharField(db_comment='创建者ID', default='admin', max_length=50, verbose_name='创建者ID'),
        ),
    ]
