# Generated by Django 5.2.17 on 2026-09-26 01:48

import prompts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingArticleIllustration',
            fields=[
                ('id', models.CharField(default=prompts.models.generate_pending_article_illustration_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('task_id', models.CharField(max_length=128)),
                ('image_url', models.URLField(max_length=2048)),
                ('error_message', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pending_article_illustrations',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'task_id'), name='pending_article_illustration_task_unique')],
            },
        ),
    ]
