# Generated by Django 5.2.17 on 2026-09-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_pendingarticleillustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingarticleillustration',
            name='model_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='pendingarticleillustration',
            name='preview_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingarticleillustration',
            name='provider_type',
            field=models.CharField(default='Grsai', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingarticleillustration',
            name='status',
            field=models.CharField(default='download_pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingarticleillustration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pendingarticleillustration',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
    ]
