# Generated by Django 5.2.17 on 2026-09-28 14:46

import prompts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0004_agentpostillustration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenerationTask',
            fields=[
                ('id', models.CharField(default=prompts.models.generate_pending_article_illustration_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='admin', max_length=50)),
                ('agent_key', models.CharField(blank=True, default='', max_length=40)),
                ('request_id', models.CharField(max_length=80)),
                ('input_hash', models.CharField(max_length=64)),
                ('request_data', models.JSONField(default=dict)),
                ('model_id', models.CharField(max_length=32)),
                ('provider_type', models.CharField(max_length=20)),
                ('status', models.CharField(default='submitting', max_length=32)),
                ('provider_task_id', models.CharField(blank=True, default='', max_length=128)),
                ('image_url', models.TextField(blank=True, default='')),
                ('asset_id', models.CharField(blank=True, default='', max_length=32)),
                ('error_message', models.CharField(blank=True, default='', max_length=200)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'image_generation_tasks',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'agent_key', 'request_id'), name='image_generation_request_unique')],
            },
        ),
    ]
