import {useState} from 'react';
import type {CourseData, Knowledge, Stage} from '../../types/api/learning';
import {buttonClass, cardClass, inputClass, kindName, statusName} from './presentation';

export function ExerciseList({course, history, open}: {course: CourseData; history: boolean; open: (id: string) => void}) {
    const exercises = (course.exercises || []).filter(e => history ? ['completed', 'ended', 'failed'].includes(e.status) : !['completed', 'ended', 'failed'].includes(e.status));
    return <section className={cardClass}><h2 className="mb-4 font-semibold">{history ? '学习记录' : '继续学习'}</h2>{!exercises.length && <p className="py-8 text-center text-sm text-slate-400">{history ? '完成练习后，你的成长会留在这里。' : '没有积压的练习，可以准备下一份。'}</p>}<div className="space-y-2">{exercises.map(e => <button key={e.id} onClick={() => open(e.id)} className="flex w-full items-center justify-between gap-3 rounded-xl border border-slate-100 p-4 text-left hover:border-orange-200 hover:bg-orange-50/40"><div><p className="text-sm font-medium">{e.title}</p><p className="mt-1 text-xs text-slate-400">{kindName[e.kind]} · {new Date(e.createdAt).toLocaleDateString()}</p></div><span className="shrink-0 text-xs text-orange-600">{statusName[e.status]}</span></button>)}</div></section>;
}

export function KnowledgeList({knowledge, dueOnly, open}: {knowledge: Knowledge[]; dueOnly: boolean; open: (id: string) => void}) {
    const points = dueOnly ? knowledge.filter(p => p.status === '需复习' || (p.lastScore !== null && p.lastScore < 80)) : knowledge;
    return <section className={cardClass}><h2 className="font-semibold">{dueOnly ? '回顾与错题' : '知识点画像'}</h2><p className="mt-1 text-xs text-slate-400">依据正式作答记录评估；到期只提示复习，不自动记错。</p>{!points.length && <p className="py-8 text-center text-sm text-slate-400">{dueOnly ? '暂时没有需要回顾的知识点。' : '完成初测后逐步建立学习画像。'}</p>}<div className="mt-4 space-y-3">{points.map(p => <details key={p.id} className="rounded-xl border border-slate-100 p-4"><summary className="flex cursor-pointer items-center justify-between gap-3 text-sm"><span>{p.name}</span><span className={p.status === '需复习' ? 'text-orange-600' : 'text-slate-400'}>{p.status}</span></summary><p className="mt-3 text-xs text-slate-500">最近得分 {p.lastScore ?? '—'} · 下次复习 {p.dueAt ? new Date(p.dueAt).toLocaleDateString() : '待评估'}</p>{p.evidence.map(e => <button key={e.attemptId} onClick={() => open(e.exerciseId)} className="mt-2 block text-left text-xs text-orange-600">{e.date} · {e.score}分 · {e.assisted ? '辅助作答' : '独立作答'}{e.review ? ' · 到期复习' : ''} → 查看依据</button>)}</details>)}</div></section>;
}

export function PlanEditor({course, busy, save}: {course: CourseData; busy: boolean; save: (stages: Stage[], stage: number) => Promise<void>}) {
    const plan = course.plan;
    const [editing, setEditing] = useState(false);
    const [stages, setStages] = useState<Stage[]>([]);
    const [stage, setStage] = useState(0);
    const [error, setError] = useState('');
    if (!plan) return <section className={cardClass}><h2 className="font-semibold">从一次轻量初测开始</h2><p className="mt-3 text-sm leading-relaxed text-slate-500">老师会结合你的目标和初测表现，提出三个阶段的学习重点。初测是起点，不是正式水平认证。</p></section>;
    return <section className={cardClass}><div className="flex items-center justify-between"><h2 className="font-semibold">{plan.confirmed ? '阶段学习计划' : '确认你的学习计划'}</h2><button disabled={busy} className="text-sm text-orange-600" onClick={() => {setStages(plan.stages); setStage(plan.stage); setEditing(true);}}>调整计划</button></div><ol className="mt-4 space-y-4">{plan.stages.map((s, i) => <li key={i} className={`rounded-xl p-4 ${i === plan.stage ? 'bg-orange-50' : 'bg-slate-50'}`}><p className="text-sm font-semibold">{i + 1}. {s.title}</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-500">{s.focus}</p></li>)}</ol><p className="mt-3 text-xs text-slate-400">当前阶段已完成 {course.stageCompleted || 0}/5 份练习；阶段评估后由你确认下一步。</p>{!plan.confirmed && <button disabled={busy} className={`${buttonClass} mt-4`} onClick={() => void save(plan.stages, plan.stage)}>确认并开始学习</button>}
        {plan.confirmed && course.stageEvaluationDue && plan.stage < 2 && <button disabled={busy} className={`${buttonClass} mt-4`} onClick={() => {setStages(plan.stages); setStage(plan.stage + 1); setEditing(true);}}>确认下一阶段</button>}
        {editing && <div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-900/40 p-4"><form className="max-h-[85vh] w-full max-w-xl space-y-4 overflow-y-auto rounded-2xl bg-white p-6 scrollbar-hide" onSubmit={async e => {e.preventDefault(); setError(''); try {await save(stages, stage); setEditing(false);} catch (err) {setError(err instanceof Error ? err.message : '保存失败');}}}><h2 className="font-bold">调整阶段计划</h2>{stages.map((s, i) => <div key={i}><label className="text-xs text-slate-500">阶段 {i + 1}<input aria-label={`阶段${i + 1}标题`} required maxLength={100} className={`${inputClass} mt-1`} value={s.title} onChange={e => setStages(prev => prev.map((v, j) => j === i ? {...v, title: e.target.value} : v))}/></label><textarea aria-label={`阶段${i + 1}重点`} required maxLength={1000} className={`${inputClass} mt-2 resize-none`} rows={2} value={s.focus} onChange={e => setStages(prev => prev.map((v, j) => j === i ? {...v, focus: e.target.value} : v))}/></div>)}<fieldset><legend className="text-xs text-slate-500">当前学习阶段</legend><div className="mt-2 flex gap-4">{stages.map((_, i) => <label key={i} className="text-sm"><input type="radio" name="stage" checked={stage === i} onChange={() => setStage(i)}/> {i + 1}</label>)}</div></fieldset>{error && <p className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-3"><button type="button" disabled={busy} onClick={() => setEditing(false)}>取消</button><button disabled={busy} className={buttonClass}>保存并确认</button></div></form></div>}
    </section>;
}

export function ProfilePanel({course, busy, evaluate, correct}: {course: CourseData; busy: boolean; evaluate: () => void; correct: (value: string) => Promise<void>}) {
    const [editing, setEditing] = useState(false);
    const [content, setContent] = useState('');
    const [error, setError] = useState('');
    return <section className={cardClass}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">老师的整体评估</h2><div className="flex gap-3"><button disabled={busy} className="text-sm text-slate-500" onClick={() => setEditing(true)}>补充／纠正画像</button><button disabled={busy || course.requests?.some(r => r.kind === 'evaluate' && ['pending', 'running'].includes(r.status))} className={buttonClass} onClick={evaluate}>生成阶段评估</button></div></div>
        <div className="mt-4 rounded-xl bg-orange-50 p-4"><p className="text-sm font-medium">动态学习评估 · {course.assessment?.status || '待初测'}</p><p className="mt-2 text-xs text-slate-500">起始自评：{course.config?.level || '不确定'}，仅作初测参考。后续按各知识点表现调整难度，不代表考试等级。</p>{course.assessment?.points.map(p => <div key={p.id} className="mt-3 text-sm"><p>{p.name} · {p.guidance}</p><p className="mt-1 text-xs text-slate-500">{p.reason}</p></div>)}</div>
        {!course.evaluations?.length && <p className="mt-4 text-sm text-slate-400">完成一些练习后，让老师结合记录分析进步与薄弱点。</p>}{course.evaluations?.map(v => <article key={v.id} className="mt-4 rounded-xl bg-slate-50 p-4"><p className="mb-2 text-xs text-slate-400">{new Date(v.createdAt).toLocaleString()}</p><p className="whitespace-pre-wrap text-sm leading-relaxed">{v.result.summary}</p><p className="mt-3 text-sm text-orange-700">下一步：{v.result.nextFocus}</p><p className="mt-2 text-xs text-slate-400">依据 {v.evidence.length} 次作答，具体记录见知识点画像。</p></article>)}
        {course.corrections?.map(v => <p key={v.id} className="mt-3 text-xs text-slate-500">我的补充：{v.content}</p>)}
        {editing && <div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-900/40 p-4"><form className={`${cardClass} w-full max-w-lg space-y-4`} onSubmit={async e => {e.preventDefault(); try {await correct(content); setContent(''); setEditing(false);} catch (err) {setError(err instanceof Error ? err.message : '保存失败');}}}><h2 className="font-semibold">补充或纠正老师判断</h2><textarea required aria-label="画像修正说明" maxLength={1000} rows={4} className={`${inputClass} resize-none`} placeholder="例如：这次拼写错误是打字失误，我想多练工作邮件。" value={content} onChange={e => setContent(e.target.value)}/><p className="text-xs text-slate-400">保留原始作答，老师会在后续评估中参考你的说明。</p>{error && <p className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={() => setEditing(false)}>取消</button><button disabled={busy} className={buttonClass}>保存说明</button></div></form></div>}
    </section>;
}
