import assert from 'node:assert/strict';
import test from 'node:test';
import rehypeSanitize from 'rehype-sanitize';

import {
    getSafeIframeUrl,
    getSafeVideoUrl,
    markdownSanitizeSchema,
} from './markdownSecurity.ts';

Object.defineProperty(globalThis, 'window', {
    configurable: true,
    value: {location: {origin: 'https://o-doc.example'}},
});

test('allows the Bilibili player generated by the editor', () => {
    assert.equal(
        getSafeIframeUrl('https://player.bilibili.com/player.html?bvid=BV1xx'),
        'https://player.bilibili.com/player.html?bvid=BV1xx',
    );
});

test('rejects executable, insecure, and unknown iframe sources', () => {
    assert.equal(getSafeIframeUrl('javascript:alert(1)'), null);
    assert.equal(getSafeIframeUrl('http://player.bilibili.com/player.html?bvid=BV1xx'), null);
    assert.equal(getSafeIframeUrl('https://example.com/embed'), null);
});

test('allows http, https, and same-origin video sources only', () => {
    assert.equal(getSafeVideoUrl('/api/resource/view/video-id'), '/api/resource/view/video-id');
    assert.equal(getSafeVideoUrl('https://cdn.example.com/video.mp4'), 'https://cdn.example.com/video.mp4');
    assert.equal(getSafeVideoUrl('javascript:alert(1)'), null);
    assert.equal(getSafeVideoUrl('data:text/html,boom'), null);
});

test('schema keeps controlled media and strips executable tags by default', () => {
    assert.ok(markdownSanitizeSchema.tagNames?.includes('iframe'));
    assert.ok(markdownSanitizeSchema.tagNames?.includes('video'));
    assert.ok(markdownSanitizeSchema.strip?.includes('script'));
    assert.ok(!markdownSanitizeSchema.attributes?.iframe?.includes('onLoad'));
});

test('schema preserves only the existing article presentation classes', () => {
    const spanAttributes = markdownSanitizeSchema.attributes?.span || [];
    const classRule = spanAttributes.find(attribute => Array.isArray(attribute) && attribute[0] === 'className');

    assert.deepEqual(classRule, [
        'className',
        'md-tag-inline',
        'custom-underline-red',
        'custom-underline-wavy',
        'custom-watercolor',
    ]);
});

test('schema preserves only the supported quote variants', () => {
    const blockquoteAttributes = markdownSanitizeSchema.attributes?.blockquote || [];
    const variantRule = blockquoteAttributes.find(
        attribute => Array.isArray(attribute) && attribute[0] === 'data-quote-variant',
    );

    assert.deepEqual(variantRule, [
        'data-quote-variant',
        'danger',
        'warning',
        'info',
    ]);
});

test('sanitizer keeps supported article styles and removes unknown values', () => {
    const sanitize = rehypeSanitize(markdownSanitizeSchema);
    const result = sanitize({
        type: 'root',
        children: [
            {
                type: 'element',
                tagName: 'span',
                properties: {className: ['md-tag-inline', 'unknown-class']},
                children: [],
            },
            {
                type: 'element',
                tagName: 'blockquote',
                properties: {'data-quote-variant': 'danger'},
                children: [],
            },
        ],
    });

    const [span, blockquote] = result.children;
    if (span?.type !== 'element' || blockquote?.type !== 'element') {
        assert.fail('expected sanitized element nodes');
    }
    assert.deepEqual(span.properties, {className: ['md-tag-inline']});
    assert.deepEqual(blockquote.properties, {'data-quote-variant': 'danger'});
});
