# Generated by Django 5.2.17 on 2026-10-09 14:24

import django.db.models.deletion
import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anthology', '0008_alter_anthology_type'),
        ('system_settings', '0054_cookingcatalog_cookingintegrity_cookingoperation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.CharField(default=learning.models.stable_id, max_length=40, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('assisted', models.JSONField(default=list)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('review_requested', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('anthology', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='anthology.anthology')),
                ('goal', models.CharField(max_length=1000)),
                ('subject', models.CharField(default='english', max_length=20)),
                ('scenarios', models.JSONField(default=list)),
                ('level', models.CharField(default='基础', max_length=40)),
                ('minutes', models.PositiveIntegerField(default=10)),
                ('question_count', models.PositiveIntegerField(default=5)),
                ('pending_limit', models.PositiveIntegerField(default=2)),
                ('teacher_name', models.CharField(default='英语老师', max_length=50)),
                ('style', models.CharField(default='耐心讲解，结合实际应用', max_length=500)),
                ('schedule_time', models.CharField(default='09:00', max_length=5)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_settings.aimodel')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('target_id', models.CharField(max_length=40)),
                ('snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learning.course')),
                ('enabled', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(null=True)),
                ('owner', models.CharField(blank=True, default='', max_length=40)),
                ('enabled_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.CharField(default=learning.models.stable_id, max_length=40, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(default=learning.models.stable_id, max_length=40, primary_key=True, serialize=False)),
                ('question_id', models.CharField(blank=True, default='', max_length=40)),
                ('role', models.CharField(default='user', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.attempt')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceJob',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learning.request')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.CharField(default=learning.models.stable_id, max_length=40, primary_key=True, serialize=False)),
                ('evidence', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.CharField(default=learning.models.stable_id, max_length=40, primary_key=True, serialize=False)),
                ('kind', models.CharField(default='practice', max_length=20)),
                ('title', models.CharField(default='正在准备练习', max_length=160)),
                ('introduction', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(default=dict)),
                ('questions', models.JSONField(default=list)),
                ('status', models.CharField(default='generating', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.exercise'),
        ),
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.CharField(default=learning.models.stable_id, max_length=40, primary_key=True, serialize=False)),
                ('stages', models.JSONField(default=list)),
                ('stage', models.PositiveIntegerField(default=0)),
                ('confirmed', models.BooleanField(default=False)),
                ('baseline', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.CharField(default=learning.models.stable_id, max_length=40, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.attempt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'version'), name='learning_grade_version')],
            },
        ),
    ]
