# Generated by Django 5.2.17 on 2026-10-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(default='不确定', max_length=40),
        ),
    ]
