# Generated by Django 5.2.17 on 2026-10-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthology', '0008_alter_anthology_type'),
        ('learning', '0002_alter_course_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalProposal',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.CharField(blank=True, default='', max_length=250)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anthology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anthology.anthology')),
            ],
        ),
        migrations.CreateModel(
            name='GoalJob',
            fields=[
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learning.goalproposal')),
                ('owner', models.CharField(blank=True, default='', max_length=40)),
                ('claimed_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
