# Generated by Django 5.2.17 on 2026-09-22

import django.utils.timezone
import utils.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('id', models.CharField(db_comment='跨设备稳定的白板标识', default=utils.id_generator.generate_whiteboard_id, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='白板 ID')),
                ('user_id', models.CharField(db_comment='业务用户标识', default='admin', max_length=50, verbose_name='创建者 ID')),
                ('title', models.CharField(db_comment='白板标题', default='未命名白板', max_length=120, verbose_name='标题')),
                ('description', models.TextField(blank=True, db_comment='白板描述', default='', verbose_name='描述')),
                ('nodes', models.JSONField(db_comment='画布节点快照', default=list, verbose_name='节点')),
                ('edges', models.JSONField(db_comment='画布连线快照', default=list, verbose_name='连线')),
                ('view_offset', models.JSONField(db_comment='画布视图位置', default=dict, verbose_name='视图偏移')),
                ('scale', models.FloatField(db_comment='画布缩放比例', default=1, verbose_name='缩放比例')),
                ('insights', models.JSONField(blank=True, db_comment='白板 AI 洞察与对话记录', null=True, verbose_name='AI 洞察')),
                ('is_valid', models.BooleanField(db_comment='软删除标识', default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(db_comment='白板创建时间', default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='白板更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '灵感白板',
                'verbose_name_plural': '灵感白板',
                'db_table': 'whiteboards',
                'db_table_comment': '灵感白板表',
                'ordering': ['-updated_at'],
            },
        ),
    ]
