# Generated by Django 5.2.17 on 2026-09-15 21:22

import book_analysis.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anthology', '0007_book_collection_and_reading_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAnalysis',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='anthology.book')),
                ('mode', models.CharField(default='knowledge', max_length=16)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('inspection', models.JSONField(default=dict)),
                ('published_revision', models.CharField(blank=True, max_length=64)),
                ('settings_version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_hash', models.CharField(max_length=64)),
                ('ordinal', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('char_count', models.PositiveIntegerField()),
                ('locator', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anthology.book')),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('canonical_id', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('aliases', models.JSONField(default=list)),
                ('facts', models.JSONField(default=list)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('time_label', models.CharField(blank=True, max_length=255)),
                ('time_order', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerLease',
            fields=[
                ('id', models.CharField(default='book-analysis', max_length=32, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, max_length=64)),
                ('run_id', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceCache',
            fields=[
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='book_analysis.chapter')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=16)),
                ('key', models.CharField(max_length=64)),
                ('patch', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anthology.book')),
            ],
        ),
        migrations.CreateModel(
            name='NodeSource',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_analysis.chapter')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_analysis.graphnode')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.CharField(default=book_analysis.models.new_id, max_length=64, primary_key=True, serialize=False)),
                ('source_hash', models.CharField(max_length=64)),
                ('mode', models.CharField(max_length=16)),
                ('settings_version', models.PositiveIntegerField()),
                ('overview', models.JSONField(default=dict)),
                ('state', models.CharField(default='building', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anthology.book')),
            ],
        ),
        migrations.AddField(
            model_name='graphnode',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_analysis.revision'),
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=255)),
                ('evidence', models.JSONField(default=list)),
                ('context', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='book_analysis.graphnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='book_analysis.graphnode')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_analysis.revision')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterResult',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('digest', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_analysis.chapter')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_analysis.revision')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.CharField(default=book_analysis.models.new_id, max_length=64, primary_key=True, serialize=False)),
                ('chapter_ids', models.JSONField(default=list)),
                ('completed_ids', models.JSONField(default=list)),
                ('state', models.CharField(default='queued', max_length=16)),
                ('stage', models.CharField(default='等待处理', max_length=64)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('force', models.BooleanField(default=False)),
                ('kind', models.CharField(default='analyze', max_length=16)),
                ('index_state', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anthology.book')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_analysis.revision')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentCache',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_analysis.chapter')),
            ],
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['book', 'source_hash', 'ordinal'], name='book_analys_book_id_0529c2_idx'),
        ),
        migrations.AddIndex(
            model_name='graphnode',
            index=models.Index(fields=['revision', 'canonical_id'], name='book_analys_revisio_0d99bd_idx'),
        ),
        migrations.AddIndex(
            model_name='graphnode',
            index=models.Index(fields=['revision', 'kind', 'ordinal'], name='book_analys_revisio_d3c140_idx'),
        ),
        migrations.AddConstraint(
            model_name='graphnode',
            constraint=models.UniqueConstraint(fields=('revision', 'canonical_id'), name='book_node_revision_canonical'),
        ),
        migrations.AddConstraint(
            model_name='chapterresult',
            constraint=models.UniqueConstraint(fields=('revision', 'chapter'), name='book_result_revision_chapter'),
        ),
    ]
