# Generated by Django 5.2.17 on 2026-09-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphnode',
            name='ordinal',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
