# Generated by Django 5.2.17 on 2026-09-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_analysis', '0002_alter_graphnode_ordinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphnode',
            name='thread',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
