# Generated by Django 5.2.17 on 2026-09-15 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_analysis', '0003_graphnode_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(default='info', max_length=16)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='book_analysis.analysisrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'id'], name='book_analys_run_id_ffd4da_idx')],
            },
        ),
    ]
