# Generated by Django 5.2.17 on 2026-09-16 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_analysis', '0004_executionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='node_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='through_chapter',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SourceEvidence',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('quote', models.TextField()),
                ('locator', models.JSONField(default=dict)),
                ('ordinal', models.PositiveBigIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_analysis.chapter')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_analysis.revision')),
            ],
        ),
        migrations.CreateModel(
            name='EntityFact',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('attribute', models.CharField(max_length=32)),
                ('value', models.TextField()),
                ('attribution', models.CharField(default='narrator', max_length=24)),
                ('speaker', models.CharField(blank=True, max_length=255)),
                ('time_label', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='explicit', max_length=16)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_facts', to='book_analysis.graphnode')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_analysis.sourceevidence')),
            ],
        ),
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('state', models.CharField(default='pending', max_length=16)),
                ('basis', models.JSONField(default=list)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_analysis.chapter')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_analysis.revision')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='book_analysis.graphnode')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hypothesis_targets', to='book_analysis.graphnode')),
            ],
            options={
                'indexes': [models.Index(fields=['revision', 'key'], name='book_analys_revisio_715e3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileChange',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('patch', models.JSONField(default=dict)),
                ('basis', models.JSONField(default=list)),
                ('state', models.CharField(default='ready', max_length=16)),
                ('legacy', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_analysis.chapter')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_changes', to='book_analysis.graphnode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('node', 'chapter'), name='book_profile_node_chapter')],
            },
        ),
    ]
