# Generated by Django 5.2.17 on 2026-09-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_analysis', '0005_analysisrun_node_id_analysisrun_through_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='introduced_ordinal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
