# Generated by Django 5.2.9 on 2026-04-23 12:55

import django.db.models.deletion
import utils.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='aimodel',
            table_comment='AI 模型表',
        ),
        migrations.AlterModelTableComment(
            name='aiprovider',
            table_comment='AI 提供商表',
        ),
        migrations.AlterModelTableComment(
            name='systemsetting',
            table_comment='系统设置表',
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='display_name',
            field=models.CharField(blank=True, db_comment='显示名称', max_length=100, null=True, verbose_name='显示名称'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='id',
            field=models.CharField(db_comment='模型ID', default=utils.id_generator.generate_model_id, max_length=40, primary_key=True, serialize=False, verbose_name='模型ID'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='name',
            field=models.CharField(db_comment='模型实际名称', max_length=100, verbose_name='模型实际名称 (Model ID)'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.ForeignKey(db_comment='所属提供商ID', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='system_settings.aiprovider', verbose_name='所属提供商'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='type',
            field=models.CharField(choices=[('chat', '对话 (Chat)'), ('embedding', '向量化 (Embedding)'), ('rerank', '重排序 (Rerank)')], db_comment='模型类型', max_length=20, verbose_name='模型类型'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='api_key',
            field=models.CharField(blank=True, db_comment='API Key', default='', max_length=255, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='base_url',
            field=models.CharField(db_comment='API Base URL', max_length=255, verbose_name='API Base URL'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='id',
            field=models.CharField(db_comment='提供商ID', default=utils.id_generator.generate_provider_id, max_length=40, primary_key=True, serialize=False, verbose_name='提供商ID'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='name',
            field=models.CharField(db_comment='提供商名称', max_length=50, verbose_name='提供商名称'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='type',
            field=models.CharField(choices=[('OpenAi', 'OpenAI'), ('Google AI', 'Google AI'), ('Xiaomi', '小米 (Xiaomi)'), ('Qwen', '通义千问 (Qwen)'), ('Doubao', '豆包 (Doubao)'), ('DeepSeek', 'DeepSeek'), ('Ollama', 'Ollama'), ('SiliconFlow', 'SiliconFlow (硅基流动)'), ('custom', '自定义 (Custom)')], db_comment='提供商类型', max_length=20, verbose_name='提供商类型'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='description',
            field=models.CharField(blank=True, db_comment='设置说明', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(db_comment='设置键', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=models.JSONField(db_comment='设置值', default=dict),
        ),
    ]
