# Generated by Django 5.2.13 on 2026-05-29 15:02

import utils.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0009_agenttask_agentrunrecord_mcpserver_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.CharField(db_comment='技能ID', default=utils.id_generator.generate_skill_id, max_length=40, primary_key=True, serialize=False, verbose_name='技能ID')),
                ('name', models.CharField(db_comment='技能名称', max_length=80, unique=True, verbose_name='技能名称')),
                ('description', models.CharField(blank=True, db_comment='技能描述', default='', max_length=255, verbose_name='描述')),
                ('version', models.CharField(blank=True, db_comment='技能版本', default='', max_length=40, verbose_name='版本')),
                ('source', models.CharField(choices=[('skillhub', 'SkillHub'), ('local', '本地导入'), ('built_in', '内置技能')], db_comment='技能来源', default='skillhub', max_length=20, verbose_name='来源')),
                ('skill_key', models.CharField(blank=True, db_comment='系统内置技能键', default='', max_length=80, verbose_name='技能键')),
                ('entry', models.CharField(blank=True, db_comment='SkillHub URL、本地包路径或 manifest 入口', default='', max_length=255, verbose_name='入口')),
                ('prompt', models.TextField(blank=True, db_comment='技能提示词', default='', verbose_name='提示词')),
                ('enabled', models.BooleanField(db_comment='是否启用', default=True, verbose_name='是否启用')),
                ('available_in_chat', models.BooleanField(db_comment='是否可在 AI Chat 中装载', default=False, verbose_name='提供给 AI 对话')),
                ('is_system', models.BooleanField(db_comment='是否为系统内置技能', default=False, verbose_name='系统技能')),
                ('manifest', models.JSONField(blank=True, db_comment='技能 manifest', default=dict, verbose_name='Manifest')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'db_table': 'sys_skill',
                'db_table_comment': '技能配置表',
                'ordering': ['source', 'name'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='skills',
            field=models.JSONField(blank=True, db_comment='Skill 配置列表', default=list, verbose_name='技能配置'),
        ),
    ]
