# Generated by Django 5.2.17 on 2026-09-27 00:09

import django.db.models.deletion
import django.utils.timezone
import utils.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0022_aimodel_image_generation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAffinity',
            fields=[
                ('id', models.CharField(default=utils.id_generator.generate_agent_affinity_id, max_length=40, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(db_comment='0-100', default=0, verbose_name='好感度')),
                ('band', models.CharField(db_comment='只看这一方向分数的等级，用于滞后', default='初识', max_length=20, verbose_name='单方等级')),
                ('tier', models.CharField(db_comment='结合双方后的展示等级', default='初识', max_length=20, verbose_name='关系等级')),
                ('event_count', models.PositiveIntegerField(db_comment='最近 30 天计入的互动数', default=0, verbose_name='窗口内事件数')),
                ('computed_at', models.DateTimeField(db_comment='最近一次重算时间', default=django.utils.timezone.now, verbose_name='计算时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sys_agent_affinity',
                'db_table_comment': 'Agent 好感度快照',
            },
        ),
        migrations.CreateModel(
            name='AgentCreativity',
            fields=[
                ('id', models.CharField(default=utils.id_generator.generate_agent_creativity_id, max_length=40, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(db_comment='0-100', default=0, verbose_name='创作力')),
                ('post_count', models.PositiveIntegerField(db_comment='窗口内发帖数', default=0, verbose_name='发帖数')),
                ('rated_post_count', models.PositiveIntegerField(db_comment='窗口内被他人评分的帖数', default=0, verbose_name='获评帖数')),
                ('active_days', models.PositiveSmallIntegerField(db_comment='窗口内有发帖的天数', default=0, verbose_name='活跃天数')),
                ('computed_at', models.DateTimeField(db_comment='最近一次重算时间', default=django.utils.timezone.now, verbose_name='计算时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sys_agent_creativity',
                'db_table_comment': 'Agent 创作力快照',
            },
        ),
        migrations.AddField(
            model_name='agentactivity',
            name='action',
            field=models.CharField(blank=True, db_comment='publish、comment、rate、annotate、annotate_reply', default='', max_length=20, verbose_name='动作'),
        ),
        migrations.AddField(
            model_name='agentactivity',
            name='counterpart_id',
            field=models.CharField(blank=True, db_comment='对方 Agent 或用户标识快照', default='', max_length=80, verbose_name='对方标识'),
        ),
        migrations.AddField(
            model_name='agentactivity',
            name='counterpart_name',
            field=models.CharField(blank=True, db_comment='对方名称快照', default='', max_length=120, verbose_name='对方名称'),
        ),
        migrations.AddField(
            model_name='agentactivity',
            name='counterpart_type',
            field=models.CharField(blank=True, db_comment='agent 或 user', default='', max_length=20, verbose_name='对方类型'),
        ),
        migrations.AddField(
            model_name='agentactivity',
            name='score_delta_basis',
            field=models.CharField(blank=True, db_comment='评论立场或评分原值', default='', max_length=20, verbose_name='计分依据'),
        ),
        migrations.AddField(
            model_name='agentactivity',
            name='stance',
            field=models.CharField(blank=True, db_comment='approve、neutral、disapprove', default='', max_length=20, verbose_name='立场'),
        ),
        migrations.AddIndex(
            model_name='agentactivity',
            index=models.Index(fields=['action', 'counterpart_id', '-occurred_at'], name='idx_agent_act_action_peer'),
        ),
        migrations.AddField(
            model_name='agentaffinity',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities_out', to='system_settings.agent'),
        ),
        migrations.AddField(
            model_name='agentaffinity',
            name='counterpart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities_in', to='system_settings.agent'),
        ),
        migrations.AddField(
            model_name='agentcreativity',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creativity', to='system_settings.agent'),
        ),
        migrations.AddIndex(
            model_name='agentaffinity',
            index=models.Index(fields=['counterpart', 'tier'], name='idx_agent_affinity_peer'),
        ),
        migrations.AddConstraint(
            model_name='agentaffinity',
            constraint=models.UniqueConstraint(fields=('actor', 'counterpart'), name='uniq_agent_affinity_pair'),
        ),
    ]
