# Generated by Django 5.2.17 on 2026-09-27 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0024_agent_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRandomRuntime',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='random_runtime', serialize=False, to='system_settings.agenttask')),
                ('state', models.JSONField(default=dict)),
                ('lease_token', models.CharField(blank=True, default='', max_length=40)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_agent_random_runtime',
            },
        ),
        migrations.AddField(
            model_name='agentrunrecord',
            name='random_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='random_allocations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='random_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='random_period',
            field=models.CharField(choices=[('daily', '每天'), ('weekly', '每周'), ('monthly', '每月'), ('yearly', '每年')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='schedule_mode',
            field=models.CharField(choices=[('fixed', '固定调度'), ('random', '周期随机')], default='fixed', max_length=20),
        ),
    ]
