# Generated by Django 5.2.17 on 2026-09-27 17:20

from django.db import migrations, models


def backfill_cycle_snapshots(apps, schema_editor):
    runtime_model = apps.get_model('system_settings', 'AgentRandomRuntime')
    task_model = apps.get_model('system_settings', 'AgentTask')
    alias = schema_editor.connection.alias
    for runtime in runtime_model.objects.using(alias).exclude(state={}).iterator():
        state = runtime.state
        if not all(key in state for key in ('id', 'start', 'end', 'config')):
            continue
        snapshot = {key: state[key] for key in ('id', 'start', 'end', 'config')}
        snapshot['available_start'] = state.get('available_start', state['start'])
        task_model.objects.using(alias).filter(pk=runtime.task_id).update(random_cycle_snapshot=snapshot)


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0025_agent_random_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='random_cycle_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(backfill_cycle_snapshots, migrations.RunPython.noop),
    ]
