# Generated by Django 5.2.17 on 2026-09-27 22:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import system_settings.agent_world.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0026_agent_random_cycle_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCategory',
            fields=[
                ('id', models.CharField(default=system_settings.agent_world.models.world_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sort', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorldChange',
            fields=[
                ('id', models.CharField(default=system_settings.agent_world.models.world_id, max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('object_id', models.CharField(db_index=True, max_length=80)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorldIncomeConfig',
            fields=[
                ('id', models.CharField(default=system_settings.agent_world.models.world_id, max_length=64, primary_key=True, serialize=False)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField(default=False)),
                ('post_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('comment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('prize_enabled', models.BooleanField(default=False)),
                ('first_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('second_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('third_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-effective_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorldIncomeEvent',
            fields=[
                ('id', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WorldLedger',
            fields=[
                ('id', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(db_index=True, max_length=40)),
                ('agent_name', models.CharField(blank=True, max_length=50)),
                ('kind', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WorldProfession',
            fields=[
                ('id', models.CharField(default=system_settings.agent_world.models.world_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorldCategoryMigration',
            fields=[
                ('id', models.CharField(default=system_settings.agent_world.models.world_id, max_length=64, primary_key=True, serialize=False)),
                ('collection_id', models.CharField(max_length=80)),
                ('old_category', models.CharField(blank=True, max_length=50)),
                ('post_ids', models.JSONField(default=list)),
                ('performed_by', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_settings.worldcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorldMonthSettlement',
            fields=[
                ('id', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('collection_id', models.CharField(max_length=80)),
                ('month', models.CharField(max_length=7)),
                ('cutoff', models.DateTimeField()),
                ('config_id', models.CharField(blank=True, max_length=64)),
                ('ranking', models.JSONField(default=list)),
                ('awards', models.JSONField(default=list)),
                ('status', models.CharField(default='frozen', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('collection_id', 'month'), name='world_month_collection_unique')],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_settings.worldprofession'),
        ),
        migrations.CreateModel(
            name='WorldProfessionCategory',
            fields=[
                ('id', models.CharField(default=system_settings.agent_world.models.world_id, max_length=64, primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_settings.worldcategory')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='system_settings.worldprofession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profession', 'category'), name='world_profession_category_unique')],
            },
        ),
    ]
