# Generated by Django 5.2.17 on 2026-09-27 22:47

import system_settings.agent_world.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0028_agent_world_baseline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldprofessioncategory',
            name='id',
            field=models.CharField(default=system_settings.agent_world.models.world_id, max_length=140, primary_key=True, serialize=False),
        ),
    ]
