# Generated by Django 5.2.17 on 2026-09-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0029_alter_worldprofessioncategory_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='worldincomeconfig',
            constraint=models.CheckConstraint(condition=models.Q(('post_amount__gte', 0)), name='world_post_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='worldincomeconfig',
            constraint=models.CheckConstraint(condition=models.Q(('comment_amount__gte', 0)), name='world_comment_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='worldincomeconfig',
            constraint=models.CheckConstraint(condition=models.Q(('first_amount__gte', 0)), name='world_first_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='worldincomeconfig',
            constraint=models.CheckConstraint(condition=models.Q(('second_amount__gte', 0)), name='world_second_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='worldincomeconfig',
            constraint=models.CheckConstraint(condition=models.Q(('third_amount__gte', 0)), name='world_third_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='worldprofessioncategory',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gte', 0)), name='world_bonus_nonnegative'),
        ),
    ]
