# Generated by Django 5.2.17 on 2026-09-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0030_worldincomeconfig_world_post_amount_nonnegative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldmonthsettlement',
            name='collection_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
