# Generated by Django 5.2.17 on 2026-09-28 10:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0032_seed_agent_history_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentExecutionLease',
            fields=[
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system_settings.agent')),
                ('token', models.CharField(blank=True, default='', max_length=40)),
                ('until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorldActionRuntime',
            fields=[
                ('id', models.CharField(default='world', max_length=40, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, default='', max_length=40)),
                ('until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='post_category_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agent',
            name='post_collection_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='post_category_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='post_collection_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='task_kind',
            field=models.CharField(choices=[('custom', '自定义任务'), ('post_interaction', '阅读帖子并评论打分')], default='custom', max_length=40),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='world_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='WorldAction',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('actor_id', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(default='claimed', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('energy_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('consumed_at', models.DateTimeField(null=True)),
                ('effects_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_settings.agent')),
                ('record', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_settings.agentrunrecord')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_settings.agenttask')),
            ],
            options={
                'indexes': [models.Index(fields=['actor_id', 'consumed_at'], name='world_action_actor_time')],
            },
        ),
    ]
