# Generated by Django 5.2.17 on 2026-09-28 12:51

from django.db import migrations, models


def classify_travel(apps, schema_editor):
    Category = apps.get_model('system_settings', 'WorldCategory')
    for row in Category.objects.all():
        if row.name.strip().lower() in {'旅行', '旅游', '旅行分享', '旅行日记', 'travel'}:
            row.workflow_kind = 'travel'
            row.save(update_fields=['workflow_kind'])


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0033_agent_post_system_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='publish_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='worldaction',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='worldcategory',
            name='workflow_kind',
            field=models.CharField(choices=[('general', '通用发帖'), ('travel', '旅行工作流')], default='general', max_length=20),
        ),
        migrations.RunPython(classify_travel, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='agenttask',
            name='task_kind',
            field=models.CharField(choices=[('custom', '自定义任务'), ('post_interaction', '阅读帖子并评论打分'), ('post_publish', '自主选题并发帖')], default='custom', max_length=40),
        ),
    ]
