# Generated by Django 5.2.17 on 2026-09-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0034_agenttask_publish_config_worldaction_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='full_body_image',
            field=models.CharField(blank=True, db_comment='角色全身立绘或设定拆解图的资源地址，随 Agent 配置同步', default='', max_length=255, verbose_name='全身形象参考图'),
        ),
    ]
