# Generated by Django 5.2.17 on 2026-09-28 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0035_agent_full_body_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelSeedState',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('row_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelDestination',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('country', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('original_name', models.CharField(blank=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='travel_price_positive')],
            },
        ),
    ]
