# Generated by Django 5.2.17 on 2026-09-28 16:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0036_travel_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelMaterialCache',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('materials', models.JSONField(default=list)),
                ('prepared', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TravelRuntime',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=64)),
                ('until', models.DateTimeField(null=True)),
                ('next_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('photo_started_at', models.DateTimeField(null=True)),
                ('authorized', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='agenttask',
            name='travel_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='task_kind',
            field=models.CharField(choices=[('custom', '自定义任务'), ('post_interaction', '阅读帖子并评论打分'), ('post_publish', '自主选题并发帖'), ('travel', '旅行')], default='custom', max_length=40),
        ),
        migrations.CreateModel(
            name='AgentInventoryItem',
            fields=[
                ('id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('actor_id', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(default='souvenir', max_length=24)),
                ('quantity', models.PositiveIntegerField()),
                ('source', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_quantity_positive')],
            },
        ),
        migrations.CreateModel(
            name='TravelJourney',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('actor_id', models.CharField(db_index=True, max_length=40)),
                ('owner_id', models.CharField(max_length=40)),
                ('status', models.CharField(db_index=True, default='active', max_length=24)),
                ('phase', models.CharField(default='choose', max_length=24)),
                ('snapshot', models.JSONField(default=dict)),
                ('destination_id', models.CharField(blank=True, max_length=32)),
                ('departed_at', models.DateTimeField(null=True)),
                ('arrived_at', models.DateTimeField(null=True)),
                ('returned_at', models.DateTimeField(null=True)),
                ('article_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_settings.agent')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_settings.agenttask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TravelNode',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=24)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('input', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='system_settings.traveljourney')),
            ],
        ),
    ]
