# Generated by Django 5.2.17 on 2026-09-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0037_travel_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinventoryitem',
            name='owner_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
