# Generated by Django 5.2.17 on 2026-09-28 17:54

from django.db import migrations, models
from decimal import Decimal, InvalidOperation


def backfill_attributes(apps, schema_editor):
    Item = apps.get_model('system_settings', 'AgentInventoryItem')
    Agent = apps.get_model('system_settings', 'Agent')
    Journey = apps.get_model('system_settings', 'TravelJourney')
    alias = schema_editor.connection.alias
    names = dict(Agent.objects.using(alias).values_list('id', 'name'))
    for item in Item.objects.using(alias).iterator():
        source = item.source or {}
        journey = Journey.objects.using(alias).filter(pk=source.get('journey_id')).first()
        item.actor_name = names.get(item.actor_id, '')
        item.origin_actor_id = journey.actor_id if journey else item.actor_id
        item.origin_actor_name = journey.snapshot.get('agent_name', '') if journey else item.actor_name
        try:
            value = Decimal(str(source.get('unit_price', '0')))
            item.value = value if value.is_finite() and 0 <= value <= Decimal('9999999999.99') else 0
        except InvalidOperation:
            item.value = 0
        item.save(using=alias, update_fields=['actor_name', 'origin_actor_id', 'origin_actor_name', 'value'])


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0038_inventory_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinventoryitem',
            name='actor_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='agentinventoryitem',
            name='origin_actor_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='agentinventoryitem',
            name='origin_actor_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='agentinventoryitem',
            name='rarity',
            field=models.CharField(choices=[('common', '普通'), ('uncommon', '精良'), ('rare', '稀有'), ('epic', '史诗'), ('legendary', '传说')], default='common', max_length=16),
        ),
        migrations.AddField(
            model_name='agentinventoryitem',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='agentinventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='inventory_value_nonnegative'),
        ),
        migrations.RunPython(backfill_attributes, migrations.RunPython.noop),
    ]
