# Generated by Django 5.2.17 on 2026-09-29 00:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0043_inventory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentFarm',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_name', models.CharField(max_length=50)),
                ('appearance', models.JSONField(default=dict)),
                ('state', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FarmCatalog',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('seed', models.CharField(max_length=64)),
                ('rules', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='agenttask',
            name='farm_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='task_kind',
            field=models.CharField(choices=[('custom', '自定义任务'), ('post_interaction', '阅读帖子并评论打分'), ('post_publish', '自主选题并发帖'), ('travel', '旅行'), ('farm', '农场经营')], default='custom', max_length=40),
        ),
        migrations.CreateModel(
            name='FarmOperation',
            fields=[
                ('id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('opportunity_id', models.CharField(db_index=True, max_length=64)),
                ('operation', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='system_settings.agentfarm')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
