# Generated by Django 5.2.17 on 2026-09-29 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0044_agentfarm_farmcatalog_agenttask_farm_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketConfig',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('slot_count', models.PositiveIntegerField(default=8)),
                ('seed', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketIntegrity',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('hashes', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('seller_id', models.CharField(db_index=True, max_length=40)),
                ('seller_name', models.CharField(max_length=50)),
                ('item', models.JSONField(default=dict)),
                ('initial_quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='active', max_length=16)),
                ('history', models.JSONField(default=list)),
                ('operation_keys', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('repriced_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarketRuntime',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('agent_token', models.CharField(max_length=64)),
                ('process_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='agenttask',
            name='market_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='task_kind',
            field=models.CharField(choices=[('custom', '自定义任务'), ('post_interaction', '阅读帖子并评论打分'), ('post_publish', '自主选题并发帖'), ('travel', '旅行'), ('farm', '农场经营'), ('market', '市场交易')], default='custom', max_length=40),
        ),
        migrations.CreateModel(
            name='MarketBatch',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('slots', models.JSONField(default=list)),
                ('feed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_keys', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner_id', 'starts_at'), name='market_owner_hour_unique')],
            },
        ),
        migrations.CreateModel(
            name='MarketSession',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_id', models.CharField(db_index=True, max_length=40)),
                ('actor_name', models.CharField(max_length=50)),
                ('mode', models.CharField(default='mcp', max_length=16)),
                ('status', models.CharField(default='active', max_length=16)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('calls', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_settings.agentrunrecord')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_settings.agenttask')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarketTransaction',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_id', models.CharField(db_index=True, max_length=40)),
                ('actor_name', models.CharField(max_length=50)),
                ('operation', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_settings.marketsession')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
