# Generated by Django 5.2.17 on 2026-09-29 15:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0045_marketconfig_marketintegrity_marketlisting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_name', models.CharField(max_length=50)),
                ('positions', models.JSONField(default=dict)),
                ('trade_keys', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentCache',
            fields=[
                ('id', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentIntegrity',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('hashes', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='agenttask',
            name='investment_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='task_kind',
            field=models.CharField(choices=[('custom', '自定义任务'), ('post_interaction', '阅读帖子并评论打分'), ('post_publish', '自主选题并发帖'), ('travel', '旅行'), ('farm', '农场经营'), ('market', '市场交易'), ('investment', 'A 股投资')], default='custom', max_length=40),
        ),
        migrations.CreateModel(
            name='InvestmentDecision',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_id', models.CharField(db_index=True, max_length=40)),
                ('actor_name', models.CharField(max_length=50)),
                ('reference_date', models.DateField()),
                ('execution_date', models.DateField()),
                ('status', models.CharField(default='running', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('calls', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_settings.agentrunrecord')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_settings.agenttask')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentNewsClaim',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('day', models.DateField()),
                ('status', models.CharField(default='claimed', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner_id', 'day'), name='investment_news_owner_day')],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTrade',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_id', models.CharField(db_index=True, max_length=40)),
                ('actor_name', models.CharField(max_length=50)),
                ('operation', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_settings.investmentdecision')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
