# Generated by Django 5.2.17 on 2026-09-29 17:09

import django.core.validators
from django.db import migrations, models


def seed_farmer(apps, schema_editor):
    profession = apps.get_model('system_settings', 'WorldProfession')
    profession.objects.get_or_create(pk='profession:farmer', defaults={
        'name': '农民', 'description': '经营农场，作物与畜牧收获产量加成',
        'farm_yield_percentage': '20',
    })


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0046_investmentaccount_investmentcache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldprofession',
            name='farm_yield_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='worldprofession',
            constraint=models.CheckConstraint(condition=models.Q(('farm_yield_percentage__gte', 0)), name='world_farm_bonus_nonnegative'),
        ),
        migrations.RunPython(seed_farmer, migrations.RunPython.noop),
    ]
