# Generated by Django 5.2.17 on 2026-09-29 23:01

import django.db.models.deletion
import django.utils.timezone
import system_settings.agent_world.life_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0047_worldprofession_farm_yield_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeConfig',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('settings', models.JSONField(default=dict)),
                ('paused_agents', models.JSONField(default=list)),
                ('migrated', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifeCycle',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifeGoal',
            fields=[
                ('id', models.CharField(default=system_settings.agent_world.life_models.life_id, max_length=40, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_id', models.CharField(db_index=True, max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('condition', models.JSONField(default=dict)),
                ('progress', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifeProfile',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('preferences', models.TextField(blank=True)),
                ('direction', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifeItem',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_id', models.CharField(db_index=True, max_length=40)),
                ('original_at', models.DateTimeField()),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('activity', models.CharField(default='unplanned', max_length=32)),
                ('task_id', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('intent', models.TextField(blank=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('record_id', models.CharField(blank=True, max_length=40)),
                ('context', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='system_settings.lifecycle')),
            ],
        ),
        migrations.CreateModel(
            name='LifeRevision',
            fields=[
                ('id', models.CharField(default=system_settings.agent_world.life_models.life_id, max_length=40, primary_key=True, serialize=False)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='system_settings.lifeitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='lifeitem',
            index=models.Index(fields=['owner_id', 'actor_id', 'status'], name='life_owner_actor_state'),
        ),
    ]
