# Generated by Django 5.2.17 on 2026-09-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0048_unified_life_planning'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeIntegrity',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('hashes', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
