# Generated by Django 5.2.17 on 2026-09-30 12:46

import django.db.models.deletion
import django.utils.timezone
import system_settings.agent_world.life_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0051_reword_travel_memories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.CharField(default=system_settings.agent_world.life_models.life_id, max_length=40, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_id', models.CharField(max_length=100)),
                ('identity', models.JSONField(default=dict)),
                ('content', models.TextField()),
                ('images', models.JSONField(default=list)),
                ('image_state', models.JSONField(default=dict)),
                ('evidence', models.JSONField(default=list)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialConfig',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('settings', models.JSONField(default=dict)),
                ('overrides', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialEvent',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_id', models.CharField(max_length=40)),
                ('counterpart_id', models.CharField(max_length=100)),
                ('source_key', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=32)),
                ('reason', models.TextField()),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('rule_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialInbox',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('target_id', models.CharField(db_index=True, max_length=100)),
                ('sender_id', models.CharField(max_length=100)),
                ('source_kind', models.CharField(max_length=20)),
                ('source_id', models.CharField(max_length=40)),
                ('content_id', models.CharField(max_length=40)),
                ('root_id', models.CharField(blank=True, max_length=40)),
                ('identity', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialIntegrity',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('hashes', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialOpportunity',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_id', models.CharField(max_length=40)),
                ('business_date', models.DateField()),
                ('kind', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('snapshot', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='agentaffinity',
            name='score',
            field=models.SmallIntegerField(db_comment='-100至100；旧快照迁移基线', default=0, verbose_name='好感度'),
        ),
        migrations.CreateModel(
            name='MomentComment',
            fields=[
                ('id', models.CharField(default=system_settings.agent_world.life_models.life_id, max_length=40, primary_key=True, serialize=False)),
                ('actor_id', models.CharField(max_length=100)),
                ('identity', models.JSONField(default=dict)),
                ('content', models.TextField()),
                ('parent_id', models.CharField(blank=True, max_length=40)),
                ('root_id', models.CharField(blank=True, max_length=40)),
                ('reply_to_actor_id', models.CharField(blank=True, max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='system_settings.moment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialRelation',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_id', models.CharField(db_index=True, max_length=40)),
                ('counterpart_id', models.CharField(max_length=100)),
                ('counterpart_identity', models.JSONField(default=dict)),
                ('familiarity', models.PositiveSmallIntegerField(default=0)),
                ('affinity', models.SmallIntegerField(default=0)),
                ('band', models.CharField(default='中性', max_length=20)),
                ('emotion', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner_id', 'actor_id', 'counterpart_id'), name='social_relation_direction')],
            },
        ),
        migrations.CreateModel(
            name='MomentLike',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('actor_id', models.CharField(max_length=100)),
                ('identity', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=True)),
                ('rewarded', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='likes', to='system_settings.moment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('moment', 'actor_id'), name='social_like_actor')],
            },
        ),
    ]
