# Generated by Django 5.2.17 on 2026-10-09 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0053_seed_social_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingCatalog',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('rules', models.JSONField(default=dict)),
                ('item_icons', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CookingIntegrity',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('hashes', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CookingOperation',
            fields=[
                ('id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_id', models.CharField(db_index=True, max_length=40)),
                ('actor_name', models.CharField(max_length=50)),
                ('opportunity_id', models.CharField(db_index=True, max_length=64)),
                ('recipe_id', models.CharField(max_length=40)),
                ('snapshot', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CookingSkill',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_name', models.CharField(max_length=50)),
                ('experience', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='agenttask',
            name='cooking_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='task_kind',
            field=models.CharField(choices=[('custom', '自定义任务'), ('post_interaction', '阅读帖子并评论打分'), ('post_publish', '自主选题并发帖'), ('travel', '旅行'), ('farm', '农场经营'), ('market', '市场交易'), ('investment', 'A 股投资'), ('cooking', '美食制作')], default='custom', max_length=40),
        ),
    ]
