# Generated by Django 5.2.17 on 2026-10-09 17:26

from django.db import migrations, models


def initialize_stars(apps, schema_editor):
    for item in apps.get_model('system_settings', 'AgentInventoryItem').objects.all().iterator():
        if item.source.get('sku', '').startswith('crop.') and 'stars' not in item.source:
            item.source = {**item.source, 'stars': 1}
            item.save(update_fields=['source'])
    for listing in apps.get_model('system_settings', 'MarketListing').objects.filter(status='active').iterator():
        source = listing.item.get('source') or {}
        if source.get('sku', '').startswith('crop.') and 'stars' not in source:
            listing.item = {**listing.item, 'source': {**source, 'stars': 1}}
            listing.save(update_fields=['item'])
    # Existing complete asset checkpoints must reflect the non-economic normalization.
    from system_settings.agent_world.market_sync import refresh_restored_checkpoints
    from system_settings.agent_world.cooking_sync import checkpoint_all
    refresh_restored_checkpoints()
    checkpoint_all()


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0054_cookingcatalog_cookingintegrity_cookingoperation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbatch',
            name='supplies',
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(initialize_stars, migrations.RunPython.noop),
    ]
