# Generated by Django 5.2.17 on 2026-10-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0056_dish_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='thinking_mode',
            field=models.CharField(choices=[('default', '默认'), ('enabled', '开启'), ('disabled', '关闭')], default='default', max_length=16),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='thinking_protocol',
            field=models.CharField(choices=[('auto', '自动'), ('thinking', 'thinking.type'), ('enable_thinking', 'enable_thinking'), ('adaptive', 'thinking.adaptive'), ('unsupported', '不支持')], default='auto', max_length=24),
        ),
    ]
