# Generated by Django 5.2.17 on 2026-10-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0057_aimodel_thinking_mode_aimodel_thinking_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='thinking_protocol',
            field=models.CharField(choices=[('auto', '自动'), ('thinking', 'thinking.type'), ('enable_thinking', 'enable_thinking'), ('adaptive', 'thinking.adaptive'), ('reasoning_effort', 'reasoning_effort'), ('unsupported', '不支持')], default='auto', max_length=24),
        ),
    ]
