# Generated by Django 5.2.17 on 2026-10-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0058_alter_aimodel_thinking_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tasks', to='system_settings.aimodel', verbose_name='任务指定模型'),
        ),
    ]
