# Generated by Django 5.2.17 on 2026-10-10 11:33

import django.utils.timezone
import system_settings.token_usage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0059_agenttask_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTokenUsage',
            fields=[
                ('id', models.CharField(default=system_settings.token_usage.models.usage_id, max_length=40, primary_key=True, serialize=False)),
                ('agent_key', models.CharField(blank=True, default='', max_length=40)),
                ('agent_name', models.CharField(blank=True, default='系统规划', max_length=100)),
                ('task_key', models.CharField(blank=True, default='', max_length=40)),
                ('task_name', models.CharField(blank=True, default='', max_length=100)),
                ('record_key', models.CharField(blank=True, default='', max_length=40)),
                ('owner_key', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('purpose', models.CharField(default='task', max_length=40)),
                ('phase', models.CharField(blank=True, default='', max_length=100)),
                ('model_key', models.CharField(blank=True, default='', max_length=40)),
                ('model_name', models.CharField(blank=True, default='', max_length=200)),
                ('provider_key', models.CharField(blank=True, default='', max_length=40)),
                ('provider_name', models.CharField(blank=True, default='', max_length=100)),
                ('device_id', models.CharField(max_length=40)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='running', max_length=20)),
                ('input_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cached_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reasoning_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('usage_complete', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sys_agent_token_usage',
                'indexes': [models.Index(fields=['started_at', 'id'], name='token_usage_time'), models.Index(fields=['agent_key', 'started_at'], name='token_usage_agent'), models.Index(fields=['task_key', 'started_at'], name='token_usage_task'), models.Index(fields=['record_key', 'agent_key'], name='token_usage_record')],
            },
        ),
    ]
