# Generated by Django 5.2.17 on 2026-10-10 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def initialize(apps, schema_editor):
    State = apps.get_model('system_settings', 'AgentMemoryState')
    Profile = apps.get_model('system_settings', 'LifeProfile')
    Config = apps.get_model('system_settings', 'LifeConfig')
    Agent = apps.get_model('system_settings', 'Agent')
    now = django.utils.timezone.now()
    for config in Config.objects.all():
        for profile in Profile.objects.filter(owner_id=config.pk, pk__in=config.settings.get('agent_ids', [])):
            if Agent.objects.filter(pk=profile.pk).exists():
                State.objects.get_or_create(agent_id=profile.pk, defaults={'owner_id': config.pk, 'enabled_at': now})


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0060_agenttokenusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemoryLease',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=64)),
                ('until', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentMemoryState',
            fields=[
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system_settings.agent')),
                ('owner_id', models.CharField(max_length=40)),
                ('enabled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_day', models.DateField(null=True)),
                ('attempted_day', models.DateField(null=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('observations', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RunPython(initialize, migrations.RunPython.noop),
        migrations.AddField(
            model_name='agentlongtermmemory',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='固定记忆'),
        ),
    ]
