# Generated by Django 5.2.17 on 2026-10-10 20:53

import django.utils.timezone
import system_settings.agent_world.combat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0061_agentmemorylease_agentmemorystate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatCatalog',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('digest', models.CharField(max_length=64)),
                ('tables', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombatConfig',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('daily_minutes', models.PositiveIntegerField(default=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombatEncounter',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('exploration_id', models.CharField(db_index=True, max_length=64)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_id', models.CharField(db_index=True, max_length=40)),
                ('number', models.PositiveIntegerField()),
                ('monster', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombatIntegrity',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('head', models.PositiveBigIntegerField(default=0)),
                ('digest', models.CharField(blank=True, max_length=64)),
                ('frame', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CombatProfile',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_name', models.CharField(max_length=50)),
                ('catalog_id', models.CharField(max_length=64)),
                ('progression', models.JSONField(default=dict)),
                ('loadout', models.JSONField(default=dict)),
                ('hp', models.PositiveIntegerField(default=104)),
                ('mp', models.PositiveIntegerField(default=62)),
                ('recovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rest_until', models.DateTimeField(null=True)),
                ('loot_progress', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombatRuntime',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(blank=True, max_length=40)),
                ('authorized', models.BooleanField(default=False)),
                ('auto_enabled', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=64)),
                ('until', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentInstance',
            fields=[
                ('id', models.CharField(default=system_settings.agent_world.combat.models.identity, max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_id', models.CharField(db_index=True, max_length=40)),
                ('catalog_id', models.CharField(max_length=64)),
                ('template_id', models.CharField(max_length=64)),
                ('snapshot', models.JSONField(default=dict)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('bound', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agenttask',
            name='exploration_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CombatFact',
            fields=[
                ('id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_id', models.CharField(db_index=True, max_length=40)),
                ('exploration_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sequence', models.PositiveBigIntegerField()),
                ('kind', models.CharField(max_length=24)),
                ('elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(default=dict)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('actor_id', 'sequence'), name='combat_actor_fact_sequence')],
            },
        ),
        migrations.CreateModel(
            name='Exploration',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=40)),
                ('actor_id', models.CharField(db_index=True, max_length=40)),
                ('actor_name', models.CharField(max_length=50)),
                ('catalog_id', models.CharField(max_length=64)),
                ('life_item_id', models.CharField(blank=True, max_length=64)),
                ('record_id', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(db_index=True, default='preparing', max_length=24)),
                ('phase', models.CharField(default='preparing', max_length=24)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(default=1800)),
                ('elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('snapshot', models.JSONField(default=dict)),
                ('state', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('next_tick_at', models.DateTimeField(db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['preparing', 'active', 'paused', 'settling'])), fields=('actor_id',), name='combat_single_open_actor')],
            },
        ),
    ]
