# Generated by Django 5.2.17 on 2026-10-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0063_combatconfig_requests_combatruntime_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatruntime',
            name='promotion_pending',
            field=models.BooleanField(default=False),
        ),
    ]
