# Generated by Django 5.2.17 on 2026-10-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0064_combatruntime_promotion_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='memo_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='task_kind',
            field=models.CharField(choices=[('custom', '自定义任务'), ('post_interaction', '阅读帖子并评论打分'), ('post_publish', '自主选题并发帖'), ('travel', '旅行'), ('farm', '农场经营'), ('market', '市场交易'), ('investment', 'A 股投资'), ('cooking', '美食制作'), ('exploration', '迷宫探索'), ('memo_capture', '随手记')], default='custom', max_length=40),
        ),
    ]
