export type ArticleTemplate = {
    id: string;
    name: string;
    description: string;
    content: string;
};

export const ARTICLE_TEMPLATES: ArticleTemplate[] = [
    {
        id: 'blank',
        name: '空白文档',
        description: '从空正文开始写',
        content: '',
    },
    {
        id: 'tech-spec',
        name: '技术方案',
        description: '背景、目标、方案与风险',
        content: [
            '## 背景',
            '',
            '',
            '## 目标',
            '',
            '',
            '## 方案设计',
            '',
            '',
            '## 接口变更',
            '',
            '',
            '## 风险',
            '',
            '',
            '## 测试计划',
            '',
            '',
        ].join('\n'),
    },
    {
        id: 'meeting-notes',
        name: '会议纪要',
        description: '结论、行动项与负责人',
        content: [
            '## 会议目标',
            '',
            '',
            '## 结论',
            '',
            '',
            '## 行动项',
            '',
            '- [ ] 事项（负责人 / 截止日期）',
            '',
        ].join('\n'),
    },
    {
        id: 'reading-notes',
        name: '读书笔记',
        description: '观点、摘录与可实践点',
        content: [
            '## 核心观点',
            '',
            '',
            '## 摘录',
            '',
            '',
            '## 个人理解',
            '',
            '',
            '## 可实践点',
            '',
            '',
        ].join('\n'),
    },
    {
        id: 'weekly-report',
        name: '周报',
        description: '进展、风险与下周计划',
        content: [
            '## 本周进展',
            '',
            '',
            '## 问题风险',
            '',
            '',
            '## 下周计划',
            '',
            '',
            '## 需要协助',
            '',
            '',
        ].join('\n'),
    },
    {
        id: 'retro',
        name: '复盘',
        description: '过程、原因与改进',
        content: [
            '## 发生了什么',
            '',
            '',
            '## 做得好的地方',
            '',
            '',
            '## 问题与原因',
            '',
            '',
            '## 下一步改进',
            '',
            '',
        ].join('\n'),
    },
];
